(function(){
'use strict';
var root=document.getElementById('palimpsestMain');if(!root||root.dataset.ready)return;root.dataset.ready='1';
var KEY='starsilk-palimpsest-session-v1', milestones=[10,100,500,2000,4000,6000,8560];
var state={phase:'claim',witnessed:[],nacreousChoice:null,ringResolution:100,wallProgress:0,timeIndex:0,hailReceived:false,mirrorPulled:false};
var reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches,holdTimer=null,audio=null;
function q(s){return root.querySelector(s)} function qa(s){return Array.prototype.slice.call(root.querySelectorAll(s))}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))} function announce(t){var x=document.getElementById('palimpsestStatus');if(x)x.textContent=t}
function save(){try{sessionStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function load(){try{var v=JSON.parse(sessionStorage.getItem(KEY)||'null');if(v&&typeof v==='object'){Object.assign(state,v);state.wallProgress=clamp(Number(state.wallProgress)||0,0,100);state.ringResolution=clamp(Number(state.ringResolution)||100,0,100);state.timeIndex=clamp(Number(state.timeIndex)||0,0,6);if(!Array.isArray(state.witnessed))state.witnessed=[]}}catch(e){}}
function witnessed(id){if(state.witnessed.indexOf(id)<0)state.witnessed.push(id);save();renderRail()}
function phaseNo(id){return({'star-law':1,'blood-ring':2,nacreous:3,'siege-wall':4,'beyond-wall':5,'witness-record':6})[id]||0}
function renderRail(){var rail=document.getElementById('witnessRail');if(!rail)return;rail.hidden=state.phase==='claim';var n=phaseNo(state.phase);document.getElementById('railPhase').textContent=(n?String(n).padStart(2,'0'):'--')+' / 06';qa('#railMarks [data-rail]').forEach(function(el){el.classList.toggle('is-witnessed',state.witnessed.indexOf(el.dataset.rail)>=0)})}
function show(id,focus){qa('.experience-phase').forEach(function(el){el.hidden=el.dataset.phase!==id});var intro=document.getElementById('phase-claim');if(intro)intro.hidden=id!=='claim';state.phase=id;save();renderRail();var el=document.getElementById('phase-'+id);if(el&&focus!==false){el.scrollIntoView({behavior:reduced?'auto':'smooth',block:'start'});var h=el.querySelector('h1,h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true})}}}
function score(phase){if(!audio)return;var levels={claim:[.18,.07,.03],'star-law':[.24,.12,.05],'blood-ring':[.16,.05,.12],nacreous:[.13,.06,.03],'siege-wall':[.10,.025,.01],'beyond-wall':[.08,.09,.04],'witness-record':[.12,.07,.03]};var l=levels[phase]||levels.claim;audio.voices.forEach(function(v,i){v.g.gain.setTargetAtTime(l[i],audio.ctx.currentTime,.08)})}
function toggleSound(){var b=document.getElementById('soundToggle');if(audio){audio.ctx.close();audio=null;b.textContent='Enable generative score';b.setAttribute('aria-pressed','false');return}var C=window.AudioContext||window.webkitAudioContext;if(!C){announce('Generative score unavailable in this browser.');return}var ctx=new C(),master=ctx.createGain();master.gain.value=.05;master.connect(ctx.destination);var voices=[110,164.81,246.94].map(function(f,i){var o=ctx.createOscillator(),g=ctx.createGain();o.type=i?'triangle':'sine';o.frequency.value=f;o.connect(g);g.connect(master);o.start();return{o:o,g:g}});audio={ctx:ctx,voices:voices};score(state.phase);b.textContent='Disable generative score';b.setAttribute('aria-pressed','true')}
var canvas=document.getElementById('starCanvas'),ctx=canvas&&canvas.getContext('2d'),collapsed=false,pull=.15,drag=false;
function draw(){if(!ctx)return;var w=canvas.width,h=canvas.height,x=w*.43,y=h*.5,r=Math.min(w,h)*.11;ctx.clearRect(0,0,w,h);var bg=ctx.createRadialGradient(x,y,0,x,y,w*.65);bg.addColorStop(0,'#111b28');bg.addColorStop(1,'#020407');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);if(collapsed){ctx.fillStyle='#000';ctx.beginPath();ctx.arc(x,y,r*.7,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#18232b';ctx.lineWidth=8;ctx.stroke();return}ctx.shadowColor='#dff8ff';ctx.shadowBlur=r*.5;ctx.fillStyle='#effcff';ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;var px=x+r+pull*w*.30,py=y-r*.15-pull*h*.06,gr=ctx.createLinearGradient(x,y,px,py);gr.addColorStop(0,'#b6f6ff');gr.addColorStop(.35,'#0cc6ff');gr.addColorStop(1,'rgba(12,198,255,.25)');ctx.lineWidth=Math.max(7,w*.008);ctx.lineCap='round';ctx.strokeStyle=gr;ctx.beginPath();ctx.moveTo(x+r*.35,y);ctx.bezierCurveTo(x+r,y-r*.25,px-w*.08,py+h*.04,px,py);ctx.stroke()}
function fit(){if(!canvas)return;var r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(640,Math.round(r.width*d));canvas.height=Math.round(Math.max(360,r.width*.53)*d);draw()}
function collapse(){if(collapsed)return;collapsed=true;pull=1;draw();document.getElementById('extractStar').disabled=true;document.getElementById('starStatus').textContent='The star has collapsed. Restart the witness session to reset it.';document.getElementById('starSceneLabel').textContent='OBSERVED: STELLAR COLLAPSE';document.getElementById('starEvidence').hidden=false;witnessed('star-law');score('star-law');announce('Star law witnessed: Starsilk extraction caused stellar collapse.')}
if(canvas){canvas.addEventListener('pointerdown',function(e){if(collapsed)return;drag=true;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',function(e){if(!drag||collapsed)return;var r=canvas.getBoundingClientRect();pull=clamp((e.clientX-r.left-r.width*.47)/(r.width*.35),0,1);draw();if(pull>.95)collapse()});canvas.addEventListener('pointerup',function(e){drag=false;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId)});if(window.ResizeObserver)new ResizeObserver(fit).observe(canvas);else addEventListener('resize',fit);setTimeout(fit,0)}
function ring(){var v=state.ringResolution,raw=100-v;document.getElementById('ringFilter').value=String(v);document.getElementById('filterReadout').textContent=v+'%';document.getElementById('ringViz').classList.toggle('is-unfiltered',raw>=70);document.getElementById('materialLedger').classList.toggle('is-visible',raw>=45);document.getElementById('ringInterpretation').textContent=raw<35?'At this resolution, the Ring remains legible as an orbital symbol.':raw<70?'The clean geometry is resolving into rendered biosphere and population material.':'The symbol has failed. The material record is now legible.';document.getElementById('ringEvidence').hidden=raw<70;if(raw>=70)witnessed('blood-ring')}
function nacreous(choice){state.nacreousChoice=choice;save();var out=document.getElementById('nacreousResult');out.hidden=false;out.innerHTML=choice==='authorize'?'<strong>YOUR CHOICE: AUTHORIZE.</strong><p>The modeled Firewall path is selected. No morality score is applied.</p>':'<strong>YOUR CHOICE: WITHHOLD.</strong><p>You refuse the modeled Firewall path. The historical decision remains separate from yours.</p>';document.getElementById('nacreousEvidence').hidden=false;witnessed('nacreous')}
function wallNodes(){var f=document.getElementById('wallField');if(!f.children.length){for(var i=0;i<40;i++){var n=document.createElement('span');n.className='wall-node';n.setAttribute('aria-hidden','true');f.appendChild(n)}}return Array.prototype.slice.call(f.children)}
function wall(){var nodes=wallNodes(),count=Math.round(nodes.length*state.wallProgress/100);nodes.forEach(function(n,i){n.classList.toggle('is-collapsed',i<count)});document.getElementById('containmentMetric').textContent=Math.round(state.wallProgress)+'%';document.getElementById('reachMetric').textContent=Math.max(0,100-Math.round(state.wallProgress*.78))+'%';document.getElementById('wallLanguage').textContent=state.wallProgress<34?'STAR LOST':state.wallProgress<67?'SYSTEM REMOVED':'CONTAINMENT NODE COMPLETE';if(state.wallProgress>=100){document.getElementById('containButton').disabled=true;document.getElementById('wallEvidence').hidden=false;witnessed('siege-wall');score('siege-wall')}save()}
function advanceWall(v){state.wallProgress=clamp(state.wallProgress+v,0,100);wall()} function stopHold(){if(holdTimer){clearInterval(holdTimer);holdTimer=null}}
function startHold(){if(holdTimer||state.wallProgress>=100)return;advanceWall(8);holdTimer=setInterval(function(){advanceWall(5)},120)}
function time(){var y=milestones[state.timeIndex];document.getElementById('timeSlider').value=String(state.timeIndex);document.getElementById('timeValue').textContent=y===8560?'~8,560 years':'+'+y.toLocaleString()+' years';document.getElementById('contactFrame').hidden=state.timeIndex!==6;save()}
function hail(){state.hailReceived=true;save();document.getElementById('wordstreamMessage').hidden=false;document.getElementById('beyondEvidence').hidden=false;document.getElementById('receiveHail').disabled=true;witnessed('beyond-wall');score('beyond-wall')}
var evidence={tiger:['TIGER','Shard-God. Starsilk creator. Systematic heliocide answered mortal access to a vulnerability. The Hal’Ven collapses became the Siege Wall.'],saved:['SAVED','The Wall contained Drakken expansion. The same source record gives its cost as thousands of stars and trillions of lives.'],us:['US','UNRESOLVED REFERENT. Palimpsest will not decide who the word includes.'],from:['FROM','A causal containment relation is visible in this route. The preposition does not settle the moral meaning of the act.'],drakken:['THE DRAKKEN','Blood Rings remain true. So does a much later post-Mother civilization whose first substantive contact begins with an offer of aid.']};
function inspect(word){var e=evidence[word];document.getElementById('claimInspector').innerHTML='<span class="evidence-label">'+e[0]+'</span><h3>'+e[1]+'</h3>'}
function ledger(){var rows=[['STAR LAW',state.witnessed.indexOf('star-law')>=0?'experienced':'unwitnessed'],['BLOOD RING','unfiltered '+(100-state.ringResolution)+'%'],['NACREOUS VI',state.nacreousChoice||'unmade'],['SIEGE WALL',state.wallProgress>=100?'completed':Math.round(state.wallProgress)+'%'],['BEYOND WALL',state.hailReceived?'hail received':'unwitnessed'],['CLAIM','unresolved']];document.getElementById('witnessLedger').innerHTML=rows.map(function(r){return'<div><dt>'+r[0]+'</dt><dd>'+r[1]+'</dd></div>'}).join('')}
function mirror(){var f=document.getElementById('mirrorField');if(!f.children.length){for(var i=0;i<120;i++){var s=document.createElement('span');s.className='mirror-star';f.appendChild(s)}}if(state.mirrorPulled){f.classList.add('is-collapsed');document.getElementById('mirrorPull').disabled=true;document.getElementById('mirrorResult').textContent='The gesture scales. The source records billions of concurrent star dives collapsing billions of stars; their stellar data becomes material for the Partition.'}}
function restore(){ring();wall();time();mirror();if(state.nacreousChoice)nacreous(state.nacreousChoice);if(state.hailReceived)hail();if(state.witnessed.indexOf('star-law')>=0)collapse();if(state.phase==='witness-record')ledger();show(state.phase,false)}
document.getElementById('beginWitness').addEventListener('click',function(){show('star-law');score('star-law')});document.getElementById('soundToggle').addEventListener('click',toggleSound);document.getElementById('extractStar').addEventListener('click',collapse);
document.getElementById('ringFilter').addEventListener('input',function(e){state.ringResolution=Number(e.target.value);save();ring()});
qa('[data-nacreous-choice]').forEach(function(b){b.addEventListener('click',function(){nacreous(b.dataset.nacreousChoice)})});
var cb=document.getElementById('containButton');cb.addEventListener('pointerdown',startHold);cb.addEventListener('pointerup',stopHold);cb.addEventListener('pointercancel',stopHold);cb.addEventListener('click',function(){advanceWall(12)});cb.addEventListener('keydown',function(e){if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();startHold()}});cb.addEventListener('keyup',function(e){if(e.key===' '||e.key==='Enter'){e.preventDefault();stopHold()}});
document.getElementById('timeSlider').addEventListener('input',function(e){state.timeIndex=Number(e.target.value);time()});document.getElementById('continueWaiting').addEventListener('click',function(){state.timeIndex=clamp(state.timeIndex+1,0,6);time()});document.getElementById('receiveHail').addEventListener('click',hail);
qa('.continue-action[data-next]').forEach(function(b){b.addEventListener('click',function(){if(b.dataset.next==='witness-record'){witnessed('witness-record');ledger()}show(b.dataset.next);score(b.dataset.next)})});
qa('[data-final-word]').forEach(function(b){b.addEventListener('click',function(){inspect(b.dataset.finalWord)})});
document.getElementById('mirrorPull').addEventListener('click',function(){state.mirrorPulled=true;save();mirror()});
document.getElementById('restartWitness').addEventListener('click',function(){try{sessionStorage.removeItem(KEY)}catch(e){};location.reload()});
load();restore();addEventListener('pagehide',function(){stopHold();if(audio)audio.ctx.close()});
})();