/* Browser-local Revision Chamber. Speculative realities never become canon authority. */
(function(){
  'use strict';
  var panel=document.getElementById('revisionChamber'), close=document.getElementById('revisionChamberClose');
  var readerBridge=document.getElementById('readerToRevision'), witnessBridge=document.getElementById('witnessToRevision');
  var branchList=document.getElementById('revisionBranchList'), newBtn=document.getElementById('revisionNewBranch');
  var branchName=document.getElementById('revisionBranchName'), proposal=document.getElementById('revisionProposal');
  var analyzeBtn=document.getElementById('revisionAnalyze'), sacrificeBtn=document.getElementById('revisionSacrifice');
  var duplicateBtn=document.getElementById('revisionDuplicate'), deleteBtn=document.getElementById('revisionDelete');
  var compareSelect=document.getElementById('revisionCompareTarget'), compareBtn=document.getElementById('revisionCompareBtn');
  var consequences=document.getElementById('revisionConsequences'), comparison=document.getElementById('revisionComparison');
  var status=document.getElementById('revisionStatus'), importInput=document.getElementById('revisionImport');
  var exportBranchBtn=document.getElementById('revisionExportBranch'), exportWorkspaceBtn=document.getElementById('revisionExportWorkspace');
  var copyPacketBtn=document.getElementById('revisionCopyPacket');
  if(!panel||!close||!branchList||!newBtn||!branchName||!proposal||!analyzeBtn||!sacrificeBtn||!duplicateBtn||!deleteBtn||!compareSelect||!compareBtn||!consequences||!comparison||!status||!importInput||!exportBranchBtn||!exportWorkspaceBtn||!copyPacketBtn)return;

  var DATA=window.STARSILK_REVISION_DATA||{records:[],locks:[],events:[],base_url:''};
  var branches=[], activeId=null, branchCounter=0, lastOpener=readerBridge||witnessBridge||close;

  function announce(message){status.textContent=message;}
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch];});}
  function safeName(value){var clean=String(value||'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,80);return clean||'Untitled reality';}
  function regex(pattern){try{pattern=String(pattern||'');if(pattern.indexOf('(?i)')===0)pattern=pattern.slice(4);return new RegExp(pattern,'i');}catch(error){return null;}}
  function literalRegex(value){return new RegExp('(^|[^A-Za-z0-9])'+String(value).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?=$|[^A-Za-z0-9])','i');}
  function wordMatch(text,value){if(!value||String(value).trim().length<2)return false;return literalRegex(String(value).trim()).test(text);}
  function unique(items,keyFn){var seen=new Set();return items.filter(function(item){var key=keyFn(item);if(seen.has(key))return false;seen.add(key);return true;});}
  function recordAliases(record){var out=[record.stable_id,String(record.stable_id||'').replace(/-/g,' '),record.title];(record.aliases||[]).forEach(function(v){out.push(v);});return out.filter(Boolean);}
  function matchedRecords(text){return (DATA.records||[]).filter(function(record){return recordAliases(record).some(function(alias){return wordMatch(text,alias);});});}
  function applicableLocks(records){var ids=records.map(function(r){return r.stable_id;});return (DATA.locks||[]).filter(function(lock){return lock.scope==='document'||(lock.target_stable_id&&ids.indexOf(lock.target_stable_id)!==-1);});}
  function violations(text,locks){var out=[];locks.forEach(function(lock){(lock.prohibitions||[]).forEach(function(pattern){var re=regex(pattern);if(re&&re.test(text))out.push({lock_id:lock.lock_id,description:lock.description,scope:lock.scope,target_stable_id:lock.target_stable_id||null,pattern:pattern});});});return unique(out,function(v){return v.lock_id+'|'+v.pattern;});}
  function eventAliases(event){var temporal=event.temporal||{},out=[event.event_id,String(event.event_id||'').replace(/-/g,' '),event.label,temporal.exact_authored_marker,temporal.relative_marker];if(temporal.duration&&temporal.duration.authored_text)out.push(temporal.duration.authored_text);return out.filter(Boolean);}
  function matchedEvents(text){return (DATA.events||[]).filter(function(event){return eventAliases(event).some(function(alias){return wordMatch(text,alias);});});}
  function buildDOMClaims(){var out=[],source=DATA.claim_source||'src/content/sections/canon-ledger.body.html';document.querySelectorAll('#canon-ledger article.lore-record[data-lore-record]').forEach(function(article,index){var id=article.dataset.loreRecord,group=article.closest('.lore-group'),refs=[];article.querySelectorAll('a.xref-link[href^="#"]').forEach(function(a){var href=a.getAttribute('href')||'';if(href.length>1)refs.push(href.slice(1));});function text(sel){var node=article.querySelector(sel);return node?node.textContent.replace(/\s+/g,' ').trim():'';}out.push({claim_id:id,order:index+1,domain:group&&group.querySelector('h3')?group.querySelector('h3').textContent.replace(/\s+/g,' ').trim():'',tag:text('.lore-tag'),label:text('h4'),statement:text('p'),source_ref:source,source_locator:'data-lore-record="'+id+'"',authority:'authored-source',evidence_class:'authored-lore-record',entity_stable_ids:Array.from(new Set(refs))});});return out;}
  var CLAIMS=buildDOMClaims();
  var LOOM_STOP=new Set(['the','and','that','this','with','from','into','over','under','through','after','before','only','does','have','has','had','was','were','are','for','its','his','her','their','they','them','then','than','not','but','can','will','would','should','could','about','within','without','become','becomes']);
  function loomTokens(value){return String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(function(v){return v.length>=3&&!LOOM_STOP.has(v);});}
  function tokenOverlap(text,value){var hay=new Set(loomTokens(text)),seen=new Set(),count=0;loomTokens(value).forEach(function(v){if(!seen.has(v)&&hay.has(v)){seen.add(v);count+=1;}});return count;}
  function matchedClaims(text,records){var ids=new Set(records.map(function(r){return r.stable_id;}));return CLAIMS.filter(function(claim){if(wordMatch(text,claim.claim_id))return true;if((claim.entity_stable_ids||[]).some(function(id){return ids.has(id);})){return true;}var labelScore=tokenOverlap(text,claim.label),tagScore=tokenOverlap(text,claim.tag);return labelScore>=2||(labelScore>=1&&tagScore>=1);});}
  function proposalNumerics(text){var out=[],re=/\b(\d[\d,]*(?:\.\d+)?)\s*(thousand|million|billion)?\b/gi,m,scale={thousand:1000,million:1000000,billion:1000000000};while((m=re.exec(text))){var value=parseFloat(m[1].replace(/,/g,''));if(m[2])value*=scale[m[2].toLowerCase()];if(Number.isFinite(value))out.push(value);}return Array.from(new Set(out));}
  function sourceContradictions(text,claims){var proposed=proposalNumerics(text),changeCue=/\b(replace|instead|change|changed|retcon|rewrite|becomes?|became|now|rather|not|only|was|were|is|are|lasted|count|confirmed|survival)\b/i,out=[];if(!proposed.length)return out;claims.forEach(function(claim){var labelScore=tokenOverlap(text,claim.label);if(labelScore<2&&!wordMatch(text,claim.claim_id))return;var facts=((DATA.claim_numeric_facts||{})[claim.claim_id]||[]).map(Number).filter(Number.isFinite);if(!facts.length)return;var matching=proposed.filter(function(v){return facts.some(function(f){return Math.abs(f-v)<1e-9;});});var differing=proposed.filter(function(v){return !facts.some(function(f){return Math.abs(f-v)<1e-9;});});if(differing.length&&(matching.length===0||changeCue.test(text))){out.push({claim_id:claim.claim_id,label:claim.label,statement:claim.statement,source_ref:claim.source_ref,source_locator:claim.source_locator,evidence_class:'explicit-numeric-mismatch',authored_values:Array.from(new Set(facts)),proposed_values:differing});}});return unique(out,function(v){return v.claim_id;});}
  function minimumSacrifices(conflicts,sourceConflicts){var out=[];conflicts.forEach(function(c){out.push({kind:'machine-lock',id:c.lock_id,label:c.description,source:DATA.canon_lock_source||'src/canon/invariants.json'});});sourceConflicts.forEach(function(c){out.push({kind:'source-claim',id:c.claim_id,label:c.label,source:c.source_ref});});return unique(out,function(v){return v.kind+'|'+v.id;});}
  function recordMap(){var map={};(DATA.records||[]).forEach(function(r){map[r.stable_id]=r;});return map;}
  function observedMentions(records){var ids=new Set(records.map(function(r){return r.stable_id;})),map=recordMap(),out=[];document.querySelectorAll('a.xref-link[data-xref-source][data-xref-target]').forEach(function(anchor){var source=anchor.dataset.xrefSource,target=anchor.dataset.xrefTarget;if(!ids.has(source)&&!ids.has(target))return;out.push({source:source,target:target,source_title:(map[source]&&map[source].title)||source,target_title:(map[target]&&map[target].title)||target,evidence_id:anchor.id||null,evidence_href:anchor.id?('#'+anchor.id):null,kind:'mentions',evidence_class:'observed-xref'});});return unique(out,function(v){return v.source+'>'+v.target+'|'+(v.evidence_id||'');});}
  function derivedSurfaces(records,events,conflicts,claims){var base=DATA.base_url||'',out=[];records.forEach(function(r){var id=r.stable_id;out.push({path:base+'entities/'+id+'/',reason:'Canonical human permalink derivative for matched stable record.'},{path:base+'discover/packets/'+id+'.json',reason:'Source-backed context packet derivative for matched stable record.'},{path:base+'machine/entities/'+id+'.json',reason:'Machine JSON derivative for matched stable record.'},{path:base+'machine/entities/'+id+'.md',reason:'Machine Markdown derivative for matched stable record.'},{path:base+'relationships/#entity-'+id,reason:'Observed-xref evidence view for matched stable record.'});});events.forEach(function(e){out.push({path:base+'chronology/#event-'+e.event_id,reason:'Source-backed chronology derivative for matched authored event label/marker.'});});if(claims.length){out.push({path:base+'entities/canon-ledger/',reason:'Authored Canon Ledger human projection containing Loom claim evidence.'},{path:base+'discover/packets/canon-ledger.json',reason:'Proof-carrying AI context packet for the authored Canon Ledger.'});}if(conflicts.length)out.push({path:base+'canon/',reason:'Canon Inspector derivative for matched machine-enforced lock evidence.'});return unique(out,function(v){return v.path;});}
  function authoritativeReview(records,events,conflicts,claims){var out=[];records.forEach(function(r){out.push({path:r.source_ref,reason:'Matched authored record source.'});});if(claims.length&&DATA.claim_source)out.push({path:DATA.claim_source,reason:'Authored Canon Ledger source for claim-level evidence.'});if(events.length&&DATA.chronology_source)out.push({path:DATA.chronology_source,reason:'Authored chronology source for matched event evidence.'});if(conflicts.length&&DATA.canon_lock_source)out.push({path:DATA.canon_lock_source,reason:'Machine-enforced canon-lock authority for explicit conflict.'});return unique(out,function(v){return v.path;});}
  function analyzeText(text,branch){var records=matchedRecords(text),locks=applicableLocks(records),conflicts=violations(text,locks),events=matchedEvents(text),claims=matchedClaims(text,records),sourceConflicts=sourceContradictions(text,claims),mentions=observedMentions(records),derived=derivedSurfaces(records,events,conflicts,claims),authority=authoritativeReview(records,events,conflicts,claims),sacrifices=minimumSacrifices(conflicts,sourceConflicts);return {schema:'starsilk-revision-report/2',generated_at:new Date().toISOString(),branch:{id:branch.id,name:safeName(branch.name)},proposal:text,verdict:conflicts.length?'blocked-by-machine-lock':'human-decision-required',source_status:sourceConflicts.length?'source-contradiction':'no-proven-source-contradiction',boundary:'Known blast radius only; claim evidence is source-backed but non-exhaustive, and absence of a contradiction is never canon approval.',summary:{recognized_records:records.length,applicable_locks:locks.length,hard_conflicts:conflicts.length,source_claim_touchpoints:claims.length,source_contradictions:sourceConflicts.length,minimum_proven_sacrifices:sacrifices.length,chronology_touchpoints:events.length,observed_mentions:mentions.length,authoritative_review_surfaces:authority.length,derived_review_surfaces:derived.length},recognized_records:records,applicable_locks:locks,conflicts:conflicts,source_claims:claims,source_contradictions:sourceConflicts,minimum_proven_sacrifice_set:sacrifices,chronology_touchpoints:events,observed_mentions:mentions,authoritative_review:authority,derived_review:derived,unknown_consequences:['Canon significance and machine-lock significance are different concepts. A sourced claim can matter without being a machine lock.','The Canon Loom is an authored-claim evidence layer, not complete Starsilk canon. No conflict does not mean canon-compatible; no source contradiction found does not mean canon-compatible either.','Unstructured, source-local, contextual, thematic, and deliberately unknown consequences outside the Loom are not inferred.','Observed cross-references prove mentions only. They are review touchpoints, not semantic relationships or causal dependencies.']};}

  function activeBranch(){return branches.find(function(b){return b.id===activeId;})||null;}
  function nextBranchName(){branchCounter+=1;var n=branchCounter,label='';while(n>0){n-=1;label=String.fromCharCode(65+(n%26))+label;n=Math.floor(n/26);}return 'Reality '+label;}
  function createBranch(text,name){var b={id:'reality-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),name:safeName(name||nextBranchName()),proposal:String(text||'').slice(0,300000),result:null};branches.push(b);activeId=b.id;renderAll();return b;}
  function syncFields(){var b=activeBranch();if(!b)return;b.name=safeName(branchName.value);b.proposal=proposal.value.slice(0,300000);}
  function selectBranch(id){syncFields();activeId=id;renderAll();proposal.focus();}
  function currentBaselineResult(){return {schema:'starsilk-revision-report/2',branch:{id:'current-canon',name:'Current Canon'},proposal:'',verdict:'immutable-baseline',source_status:'baseline',summary:{recognized_records:0,applicable_locks:0,hard_conflicts:0,source_claim_touchpoints:0,source_contradictions:0,minimum_proven_sacrifices:0,chronology_touchpoints:0,observed_mentions:0,authoritative_review_surfaces:0,derived_review_surfaces:0},recognized_records:[],applicable_locks:[],conflicts:[],source_claims:[],source_contradictions:[],minimum_proven_sacrifice_set:[],chronology_touchpoints:[],observed_mentions:[],authoritative_review:[],derived_review:[],unknown_consequences:[]};}

  function renderBranches(){branchList.innerHTML='';branches.forEach(function(b){var button=document.createElement('button');button.type='button';button.className='revision-branch'+(b.id===activeId?' is-active':'');button.dataset.branchId=b.id;button.setAttribute('aria-pressed',String(b.id===activeId));button.innerHTML='<strong>'+esc(b.name)+'</strong><span>'+(b.result?(b.result.summary.hard_conflicts?b.result.summary.hard_conflicts+' hard conflict'+(b.result.summary.hard_conflicts===1?'':'s'):'analyzed'):'not analyzed')+'</span>';branchList.appendChild(button);});}
  function renderCompareOptions(){var previous=compareSelect.value;compareSelect.innerHTML='<option value="current-canon">Current Canon</option>';branches.forEach(function(b){if(b.id===activeId)return;var option=document.createElement('option');option.value=b.id;option.textContent=b.name;compareSelect.appendChild(option);});if(Array.from(compareSelect.options).some(function(o){return o.value===previous;}))compareSelect.value=previous;}
  function renderAll(){var b=activeBranch();if(!b){createBranch('',nextBranchName());return;}branchName.value=b.name;proposal.value=b.proposal;renderBranches();renderCompareOptions();if(b.result)renderConsequences(b.result,false);else consequences.innerHTML='<div class="revision-empty"><span class="eyebrow">Known blast radius</span><p>Analyze this speculative reality to map only the evidence the archive can prove is touched.</p></div>';comparison.hidden=true;deleteBtn.disabled=branches.length<=1;}

  function summaryMarkup(result){var s=result.summary,blocked=result.verdict==='blocked-by-machine-lock',sourceConflict=(result.source_contradictions||[]).length>0;return '<div class="revision-verdict '+(blocked?'is-blocked':'is-human')+'"><span class="eyebrow">Canonicalization status</span><strong>'+(blocked?'BLOCKED BY MACHINE LOCK':'HUMAN DECISION REQUIRED')+'</strong><p>'+(blocked?'At least one explicit applicable machine prohibition matched this proposal.':sourceConflict?'No machine lock blocked this proposal, but the Canon Loom found a direct authored-source contradiction. Human judgment is required.':'No explicit machine prohibition matched. That is not permission to canonize it; machine locks and canon significance are different concepts.')+'</p></div><div class="revision-counts"><span>Records <b>'+s.recognized_records+'</b></span><span>Machine locks <b>'+s.hard_conflicts+'</b></span><span>Source claims <b>'+s.source_claim_touchpoints+'</b></span><span>Source contradictions <b>'+s.source_contradictions+'</b></span><span>Proven sacrifices <b>'+s.minimum_proven_sacrifices+'</b></span><span>Chronology <b>'+s.chronology_touchpoints+'</b></span><span>Observed mentions <b>'+s.observed_mentions+'</b></span><span>Derived review <b>'+s.derived_review_surfaces+'</b></span></div><p class="revision-blast-note">'+esc(result.boundary)+'</p>';}
  function listMarkup(title,items,formatter,empty){return '<section class="revision-impact-group"><h4>'+esc(title)+'</h4>'+(items.length?'<ul>'+items.map(function(item){return '<li>'+formatter(item)+'</li>';}).join('')+'</ul>':'<p class="revision-empty-line">'+esc(empty||'None established by this analysis.')+'</p>')+'</section>';}
  function renderConsequences(result,sacrificeMode){var html=summaryMarkup(result);if(sacrificeMode)html+='<div class="revision-sacrifice-banner"><span class="eyebrow">What would I have to sacrifice?</span><h3>Minimum proven sacrifice set</h3><p>Only direct machine-lock or authored-source contradictions appear here. Touching a source is not the same as having to discard it.</p></div>';
    if(sacrificeMode)html+=listMarkup('Minimum proven sacrifice set',result.minimum_proven_sacrifice_set||[],function(v){return '<strong>'+esc(v.id)+'</strong> · '+esc(v.label)+'<br><code>'+esc(v.kind)+'</code> · <code>'+esc(v.source)+'</code>';},'No mandatory sacrifice is mechanically proven. That does not mean the proposal is canon-compatible.');
    html+=listMarkup('Machine-lock conflicts',result.conflicts,function(c){return '<span class="revision-conflict"><strong>'+esc(c.description)+'</strong><br><code>'+esc(c.lock_id)+'</code> · matched prohibition <code>'+esc(c.pattern)+'</code></span>';},'No explicit machine-lock conflict detected. Human review is still required.');
    html+=listMarkup('Source contradictions',result.source_contradictions||[],function(c){return '<span class="revision-source-conflict"><strong>'+esc(c.claim_id)+' · '+esc(c.label)+'</strong><br><span>'+esc(c.statement)+'</span><br><code>'+esc(c.evidence_class)+'</code> · authored <code>'+esc(c.authored_values.join(', '))+'</code> / proposal <code>'+esc(c.proposed_values.join(', '))+'</code><br><code>'+esc(c.source_ref)+' :: '+esc(c.source_locator)+'</code></span>';},'No direct authored-source contradiction is mechanically proven. This is not a compatibility verdict.');
    html+=listMarkup('Why Is This Canon? — authored claim evidence',result.source_claims||[],function(c){return '<strong>'+esc(c.claim_id)+' · '+esc(c.label)+'</strong><br><span>'+esc(c.statement)+'</span><br><code>'+esc(c.authority)+'</code> / <code>'+esc(c.evidence_class)+'</code><br><code>'+esc(c.source_ref)+' :: '+esc(c.source_locator)+'</code>';},'No authored Canon Ledger claim was mechanically matched.');
    html+=listMarkup('Authoritative surfaces to review',result.authoritative_review,function(v){return '<code>'+esc(v.path)+'</code><br><span>'+esc(v.reason)+'</span>';},'No authored source surface was mechanically matched.');
    html+=listMarkup('Chronology touchpoints',result.chronology_touchpoints,function(e){var t=e.temporal||{},bits=[t.exact_authored_marker,t.relative_marker,t.duration&&t.duration.authored_text].filter(Boolean).join(' · ');return '<strong>'+esc(e.label)+'</strong> <code>'+esc(e.event_id)+'</code>'+(bits?'<br><span>'+esc(bits)+'</span>':'');},'No authored chronology label or marker was mechanically matched.');
    html+=listMarkup('Observed mention touchpoints',result.observed_mentions,function(m){return '<strong>'+esc(m.source_title)+'</strong> → <strong>'+esc(m.target_title)+'</strong><br><span><code>mentions</code> / <code>observed-xref</code>'+(m.evidence_href?' · <a href="'+esc(m.evidence_href)+'">published evidence</a>':'')+'</span>';},'No incident observed-xref mention was found for the matched records.');
    html+=listMarkup('What Breaks If This Changes? — deterministic derivatives',result.derived_review,function(v){return '<a href="'+esc(v.path)+'">'+esc(v.path)+'</a><br><span>'+esc(v.reason)+'</span>';},'No deterministic derivative was mechanically identified.');
    html+=listMarkup('Unknown consequences',result.unknown_consequences,function(v){return esc(v);},'None.');consequences.innerHTML=html;}

  function analyzeActive(sacrificeMode){syncFields();var b=activeBranch(),text=b.proposal.trim();if(!text){announce('Write a proposed reality change before analyzing it.');proposal.focus();return;}if(text.length>300000){announce('Proposal is too large. Keep a reality under 300,000 characters.');return;}b.result=analyzeText(text,b);renderBranches();renderConsequences(b.result,!!sacrificeMode);comparison.hidden=true;announce(b.result.verdict==='blocked-by-machine-lock'?'Reality analyzed: BLOCKED BY MACHINE LOCK.':'Reality analyzed: HUMAN DECISION REQUIRED.');}

  function keySets(result){return {records:(result.recognized_records||[]).map(function(v){return v.title||v.stable_id;}),claims:(result.source_claims||[]).map(function(v){return v.claim_id;}),source_conflicts:(result.source_contradictions||[]).map(function(v){return v.claim_id;}),conflicts:(result.conflicts||[]).map(function(v){return v.lock_id;}),events:(result.chronology_touchpoints||[]).map(function(v){return v.label||v.event_id;}),mentions:(result.observed_mentions||[]).map(function(v){return (v.source_title||v.source)+' → '+(v.target_title||v.target);}),derived:(result.derived_review||[]).map(function(v){return v.path;})};}
  function earliestDivergence(a,b,targetIsCanon){var aClaims=targetIsCanon?(a.source_contradictions||[]):(a.source_claims||[]),bClaims=targetIsCanon?[]:(b.source_claims||[]),aIds=new Set(aClaims.map(function(v){return v.claim_id;})),bIds=new Set(bClaims.map(function(v){return v.claim_id;})),all=CLAIMS.filter(function(v){return aIds.has(v.claim_id)!==bIds.has(v.claim_id);}).sort(function(x,y){return (x.order||0)-(y.order||0);});if(all.length){return {kind:'source-claim',id:all[0].claim_id,label:all[0].label,note:targetIsCanon?'First direct authored-source contradiction in Canon Ledger order.':'First differing authored claim footprint in Canon Ledger order.'};}var ak=(a.conflicts||[]).map(function(v){return v.lock_id;}),bk=(b.conflicts||[]).map(function(v){return v.lock_id;}),diff=ak.concat(bk).find(function(id){return ak.indexOf(id)===-1||bk.indexOf(id)===-1;});if(diff)return {kind:'machine-lock',id:diff,label:diff,note:'First differing machine-lock footprint; lock order is not chronology.'};return null;}
  function splitSets(a,b){var as=new Set(a),bs=new Set(b);return {a:a.filter(function(v){return !bs.has(v);}),shared:a.filter(function(v){return bs.has(v);}),b:b.filter(function(v){return !as.has(v);})};}
  function comparisonRow(label,sets,aName,bName){function cell(values){return values.length?'<ul>'+values.map(function(v){return '<li>'+esc(v)+'</li>';}).join('')+'</ul>':'<span class="revision-none">None</span>';}return '<section class="revision-compare-row"><h4>'+esc(label)+'</h4><div><article><span>'+esc(aName)+' only</span>'+cell(sets.a)+'</article><article><span>Shared</span>'+cell(sets.shared)+'</article><article><span>'+esc(bName)+' only</span>'+cell(sets.b)+'</article></div></section>';}
  function compareRealities(){syncFields();var a=activeBranch();if(!a)return;if(!a.result&&a.proposal.trim())a.result=analyzeText(a.proposal.trim(),a);if(!a.result){announce('Analyze or write the active reality before comparing it.');return;}var targetId=compareSelect.value,b,targetResult;if(targetId==='current-canon'){b={id:'current-canon',name:'Current Canon'};targetResult=currentBaselineResult();}else{b=branches.find(function(item){return item.id===targetId;});if(!b){announce('Choose a comparison reality.');return;}targetResult=b.result||(b.proposal.trim()?analyzeText(b.proposal.trim(),b):currentBaselineResult());}
    var ak=keySets(a.result),bk=keySets(targetResult),divergence=earliestDivergence(a.result,targetResult,targetId==='current-canon'),html='<header><span class="eyebrow">Reality diff</span><h3>'+esc(a.name)+' ↔ '+esc(b.name)+'</h3><p>Difference, not recommendation. Shared and divergent evidence footprints only.</p></header>';html+='<div class="revision-sacrifice-banner"><span class="eyebrow">Earliest Proven Divergence</span>'+(divergence?'<h3>'+esc(divergence.id)+' · '+esc(divergence.label)+'</h3><p>'+esc(divergence.note)+' This is the earliest proven difference in the Loom evidence order, not a claim of universal causal or chronological priority.</p>':'<h3>No proven divergence in the compared evidence classes.</h3><p>Absence of a proven difference is not proof that the realities are identical.</p>')+'</div>';['records','claims','source_conflicts','conflicts','events','mentions','derived'].forEach(function(key){var label={records:'Matched records',claims:'Authored claim touchpoints',source_conflicts:'Source contradictions',conflicts:'Machine-lock conflicts',events:'Chronology touchpoints',mentions:'Observed mentions',derived:'Derived review surfaces'}[key];html+=comparisonRow(label,splitSets(ak[key],bk[key]),a.name,b.name);});comparison.innerHTML=html;comparison.hidden=false;comparison.scrollIntoView({block:'nearest'});announce('Reality comparison rendered. Earliest Proven Divergence is evidence-ordered, not a ranking or canon promotion.');}

  function packetText(result){var lines=['# Starsilk Revision Chamber Change Packet','','Reality: '+result.branch.name,'Status: '+(result.verdict==='blocked-by-machine-lock'?'BLOCKED BY MACHINE LOCK':'HUMAN DECISION REQUIRED'),'Source status: '+(result.source_status||'unknown'),result.boundary,'','## Proposed reality','',result.proposal,'','## Machine-lock conflicts'];if(result.conflicts.length)result.conflicts.forEach(function(c){lines.push('- '+c.lock_id+': '+c.description+' — matched '+c.pattern);});else lines.push('- None detected by the machine-lock subset. This is not a compatibility verdict.');lines.push('','## Source contradictions');(result.source_contradictions||[]).forEach(function(c){lines.push('- '+c.claim_id+': '+c.label+' — '+c.evidence_class+' — '+c.source_ref+' :: '+c.source_locator);});if(!(result.source_contradictions||[]).length)lines.push('- None mechanically proven. This is not a compatibility verdict.');lines.push('','## Minimum proven sacrifice set');(result.minimum_proven_sacrifice_set||[]).forEach(function(v){lines.push('- '+v.kind+' '+v.id+': '+v.label+' — '+v.source);});if(!(result.minimum_proven_sacrifice_set||[]).length)lines.push('- Empty: no mandatory sacrifice mechanically proven.');lines.push('','## Why Is This Canon? — authored claim evidence');(result.source_claims||[]).forEach(function(c){lines.push('- '+c.claim_id+': '+c.label+' — '+c.source_ref+' :: '+c.source_locator);});if(!(result.source_claims||[]).length)lines.push('- No Canon Ledger claim mechanically matched.');lines.push('','## Authoritative surfaces to review');result.authoritative_review.forEach(function(v){lines.push('- '+v.path+' — '+v.reason);});if(!result.authoritative_review.length)lines.push('- None mechanically matched.');lines.push('','## Chronology touchpoints');result.chronology_touchpoints.forEach(function(e){lines.push('- '+e.event_id+': '+e.label);});if(!result.chronology_touchpoints.length)lines.push('- None mechanically matched.');lines.push('','## Observed mention touchpoints');result.observed_mentions.forEach(function(m){lines.push('- '+m.source+' -> '+m.target+' [mentions / observed-xref]');});if(!result.observed_mentions.length)lines.push('- None mechanically matched.');lines.push('','## What Breaks If This Changes?');result.derived_review.forEach(function(v){lines.push('- '+v.path);});if(!result.derived_review.length)lines.push('- No deterministic derivative mechanically identified.');lines.push('','## Unknown consequences');result.unknown_consequences.forEach(function(v){lines.push('- '+v);});lines.push('','No action in this packet changes canon. Fork -> inspect -> decide -> propagate is a human-controlled sequence.');return lines.join('\n');}
  function canonDelta(branch){var result=branch&&branch.result;if(!branch||!result)return null;return {schema:'starsilk-canon-delta/1',project_id:'starsilk-character-dossier',delta_id:branch.id,title:safeName(branch.name),authority:'exploratory',old_state:'Current published canon/evidence baseline; exact affected source claims are listed separately.',proposed_state:result.proposal,source_claim_ids:(result.source_claims||[]).map(function(v){return v.claim_id;}),machine_lock_ids:(result.conflicts||[]).map(function(v){return v.lock_id;}),affected_stable_ids:(result.recognized_records||[]).map(function(v){return v.stable_id;}),affected_event_ids:(result.chronology_touchpoints||[]).map(function(v){return v.event_id;}),exact_literals:[],must_change:(result.minimum_proven_sacrifice_set||[]).map(function(v){return v.source+' :: '+v.id;}),must_not_change:['Generated derivatives must not become canon authority.','Machine-lock significance must remain distinct from canon significance.','Observed xref mentions must not be promoted to semantic relationships.'],unknowns:(result.unknown_consequences||[]).slice()};}
  function copyPacket(){var b=activeBranch();if(!b||!b.result){announce('Analyze the active reality before copying a change packet.');return;}var text=packetText(b.result);if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(text).then(function(){announce('Change packet copied.');}).catch(function(){announce('Clipboard copy was blocked by this browser.');});else announce('Clipboard access is unavailable in this browser.');}
  function download(name,payload){var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url);},0);}
  function exportBranch(){syncFields();var b=activeBranch();if(!b)return;download('starsilk-revision-'+b.id+'.json',{schema:'starsilk-revision-branch/2',name:b.name,proposal:b.proposal,result:b.result,canon_delta:canonDelta(b)});announce('Active speculative reality and exploratory Canon Delta exported. Nothing was canonized.');}
  function exportWorkspace(){syncFields();download('starsilk-revision-workspace.json',{schema:'starsilk-revision-workspace/1',exported_at:new Date().toISOString(),branches:branches.map(function(b){return {name:b.name,proposal:b.proposal,result:b.result};})});announce('Speculative workspace exported. No canon state was included or changed.');}
  function importWorkspace(file){if(!file)return;if(file.size>4000000){announce('Workspace file is too large.');importInput.value='';return;}file.text().then(function(text){var data=JSON.parse(text),items=[];if(data.schema==='starsilk-revision-workspace/1'&&Array.isArray(data.branches))items=data.branches;else if(data.schema==='starsilk-revision-branch/1'||data.schema==='starsilk-revision-branch/2')items=[data];else throw new Error('schema');if(!items.length||items.length>12)throw new Error('count');var imported=[];items.forEach(function(item){var text=String(item.proposal||'');if(text.length>300000)throw new Error('proposal');branchCounter+=1;imported.push({id:'reality-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),name:safeName(item.name||nextBranchName()),proposal:text,result:null});});branches=imported;activeId=branches[0].id;renderAll();announce('Imported '+branches.length+' speculative realit'+(branches.length===1?'y':'ies')+'. Results will be recomputed from the current archive.');}).catch(function(){announce('That file is not a valid Revision Chamber workspace.');}).finally(function(){importInput.value='';});}
  function setOpen(open,focus){panel.hidden=!open;if(open){if(!activeBranch())createBranch('',nextBranchName());if(focus)proposal.focus();}else if(focus&&lastOpener&&typeof lastOpener.focus==='function')lastOpener.focus();}
  function openFromReader(){lastOpener=document.getElementById('readerWorkbenchToggle')||readerBridge;var readerClose=document.getElementById('readerWorkbenchClose');if(readerClose)readerClose.click();if(!activeBranch())createBranch('',nextBranchName());setOpen(true,true);}
  function openFromWitness(){lastOpener=document.getElementById('witnessEngineToggle')||witnessBridge;var witnessDraft=document.getElementById('witnessDraft'),text=witnessDraft?witnessDraft.value:'';var witnessClose=document.getElementById('witnessEngineClose');if(witnessClose)witnessClose.click();var b=activeBranch();if(branches.length===1&&b&&!b.proposal.trim()&&!b.result){b.proposal=text;renderAll();}else createBranch(text,nextBranchName());setOpen(true,true);announce(text.trim()?'Forked the Witness draft into a speculative reality. Nothing was canonized.':'Created a blank speculative reality.');}

  branchList.addEventListener('click',function(event){var button=event.target.closest('[data-branch-id]');if(button)selectBranch(button.dataset.branchId);});
  newBtn.addEventListener('click',function(){syncFields();createBranch('',nextBranchName());announce('New speculative reality forked in browser memory.');proposal.focus();});
  branchName.addEventListener('change',function(){syncFields();renderBranches();renderCompareOptions();});
  proposal.addEventListener('input',function(){var b=activeBranch();if(b){b.proposal=proposal.value.slice(0,300000);b.result=null;renderBranches();comparison.hidden=true;}});
  analyzeBtn.addEventListener('click',function(){analyzeActive(false);});
  sacrificeBtn.addEventListener('click',function(){analyzeActive(true);});
  duplicateBtn.addEventListener('click',function(){syncFields();var b=activeBranch();if(!b)return;createBranch(b.proposal,b.name+' — fork');announce('Reality duplicated. The fork is independent and still speculative.');});
  deleteBtn.addEventListener('click',function(){if(branches.length<=1){announce('Keep at least one speculative reality in the chamber.');return;}var index=branches.findIndex(function(b){return b.id===activeId;});branches=branches.filter(function(b){return b.id!==activeId;});activeId=branches[Math.max(0,index-1)].id;renderAll();announce('Speculative reality discarded. Canon was never touched.');});
  compareBtn.addEventListener('click',compareRealities);
  copyPacketBtn.addEventListener('click',copyPacket);
  exportBranchBtn.addEventListener('click',exportBranch);
  exportWorkspaceBtn.addEventListener('click',exportWorkspace);
  importInput.addEventListener('change',function(){importWorkspace(importInput.files&&importInput.files[0]);});
  close.addEventListener('click',function(){syncFields();setOpen(false,true);});
  if(readerBridge)readerBridge.addEventListener('click',openFromReader);
  if(witnessBridge)witnessBridge.addEventListener('click',openFromWitness);
  document.addEventListener('keydown',function(event){if(event.key==='Escape'&&!panel.hidden){event.preventDefault();syncFields();setOpen(false,true);return;}if((event.ctrlKey||event.metaKey)&&event.shiftKey&&event.key.toLowerCase()==='r'){event.preventDefault();lastOpener=document.getElementById('readerWorkbenchToggle')||readerBridge||close;if(panel.hidden){if(!activeBranch())createBranch('',nextBranchName());setOpen(true,true);}else setOpen(false,true);}});

  createBranch('',nextBranchName());
})();
