/* Browser-local Revision Chamber. Speculative realities never become canon authority. */
(function(){
  'use strict';
  var panel=document.getElementById('revisionChamber'), close=document.getElementById('revisionChamberClose');
  var readerBridge=document.getElementById('readerToRevision'), witnessBridge=document.getElementById('witnessToRevision');
  var branchList=document.getElementById('revisionBranchList'), newBtn=document.getElementById('revisionNewBranch');
  var branchName=document.getElementById('revisionBranchName'), proposal=document.getElementById('revisionProposal');
  var analyzeBtn=document.getElementById('revisionAnalyze'), sacrificeBtn=document.getElementById('revisionSacrifice');
  var duplicateBtn=document.getElementById('revisionDuplicate'), deleteBtn=document.getElementById('revisionDelete');
  var compareSelect=document.getElementById('revisionCompareTarget'), compareBtn=document.getElementById('revisionCompareBtn');
  var consequences=document.getElementById('revisionConsequences'), comparison=document.getElementById('revisionComparison');
  var status=document.getElementById('revisionStatus'), importInput=document.getElementById('revisionImport');
  var exportBranchBtn=document.getElementById('revisionExportBranch'), exportWorkspaceBtn=document.getElementById('revisionExportWorkspace');
  var copyPacketBtn=document.getElementById('revisionCopyPacket');
  if(!panel||!close||!branchList||!newBtn||!branchName||!proposal||!analyzeBtn||!sacrificeBtn||!duplicateBtn||!deleteBtn||!compareSelect||!compareBtn||!consequences||!comparison||!status||!importInput||!exportBranchBtn||!exportWorkspaceBtn||!copyPacketBtn)return;

  var DATA=window.STARSILK_REVISION_DATA||{records:[],locks:[],events:[],base_url:''};
  var branches=[], activeId=null, branchCounter=0, lastOpener=readerBridge||witnessBridge||close;

  function announce(message){status.textContent=message;}
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch];});}
  function safeName(value){var clean=String(value||'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,80);return clean||'Untitled reality';}
  function regex(pattern){try{pattern=String(pattern||'');if(pattern.indexOf('(?i)')===0)pattern=pattern.slice(4);return new RegExp(pattern,'i');}catch(error){return null;}}
  function literalRegex(value){return new RegExp('(^|[^A-Za-z0-9])'+String(value).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?=$|[^A-Za-z0-9])','i');}
  function wordMatch(text,value){if(!value||String(value).trim().length<2)return false;return literalRegex(String(value).trim()).test(text);}
  function unique(items,keyFn){var seen=new Set();return items.filter(function(item){var key=keyFn(item);if(seen.has(key))return false;seen.add(key);return true;});}
  function recordAliases(record){var out=[record.stable_id,String(record.stable_id||'').replace(/-/g,' '),record.title];(record.aliases||[]).forEach(function(v){out.push(v);});return out.filter(Boolean);}
  function matchedRecords(text){return (DATA.records||[]).filter(function(record){return recordAliases(record).some(function(alias){return wordMatch(text,alias);});});}
  function applicableLocks(records){var ids=records.map(function(r){return r.stable_id;});return (DATA.locks||[]).filter(function(lock){return lock.scope==='document'||(lock.target_stable_id&&ids.indexOf(lock.target_stable_id)!==-1);});}
  function violations(text,locks){var out=[];locks.forEach(function(lock){(lock.prohibitions||[]).forEach(function(pattern){var re=regex(pattern);if(re&&re.test(text))out.push({lock_id:lock.lock_id,description:lock.description,scope:lock.scope,target_stable_id:lock.target_stable_id||null,pattern:pattern});});});return unique(out,function(v){return v.lock_id+'|'+v.pattern;});}
  function eventAliases(event){var temporal=event.temporal||{},out=[event.event_id,String(event.event_id||'').replace(/-/g,' '),event.label,temporal.exact_authored_marker,temporal.relative_marker];if(temporal.duration&&temporal.duration.authored_text)out.push(temporal.duration.authored_text);return out.filter(Boolean);}
  function matchedEvents(text){return (DATA.events||[]).filter(function(event){return eventAliases(event).some(function(alias){return wordMatch(text,alias);});});}
  function recordMap(){var map={};(DATA.records||[]).forEach(function(r){map[r.stable_id]=r;});return map;}
  function observedMentions(records){var ids=new Set(records.map(function(r){return r.stable_id;})),map=recordMap(),out=[];document.querySelectorAll('a.xref-link[data-xref-source][data-xref-target]').forEach(function(anchor){var source=anchor.dataset.xrefSource,target=anchor.dataset.xrefTarget;if(!ids.has(source)&&!ids.has(target))return;out.push({source:source,target:target,source_title:(map[source]&&map[source].title)||source,target_title:(map[target]&&map[target].title)||target,evidence_id:anchor.id||null,evidence_href:anchor.id?('#'+anchor.id):null,kind:'mentions',evidence_class:'observed-xref'});});return unique(out,function(v){return v.source+'>'+v.target+'|'+(v.evidence_id||'');});}
  function derivedSurfaces(records,events,conflicts){var base=DATA.base_url||'',out=[];records.forEach(function(r){var id=r.stable_id;out.push({path:base+'entities/'+id+'/',reason:'Canonical human permalink derivative for matched stable record.'},{path:base+'discover/packets/'+id+'.json',reason:'Source-backed context packet derivative for matched stable record.'},{path:base+'machine/entities/'+id+'.json',reason:'Machine JSON derivative for matched stable record.'},{path:base+'machine/entities/'+id+'.md',reason:'Machine Markdown derivative for matched stable record.'},{path:base+'relationships/#entity-'+id,reason:'Observed-xref evidence view for matched stable record.'});});events.forEach(function(e){out.push({path:base+'chronology/#event-'+e.event_id,reason:'Source-backed chronology derivative for matched authored event label/marker.'});});if(conflicts.length)out.push({path:base+'canon/',reason:'Canon Inspector derivative for matched machine-enforced lock evidence.'});return unique(out,function(v){return v.path;});}
  function authoritativeReview(records,events,conflicts){var out=[];records.forEach(function(r){out.push({path:r.source_ref,reason:'Matched authored record source.'});});if(events.length&&DATA.chronology_source)out.push({path:DATA.chronology_source,reason:'Authored chronology source for matched event evidence.'});if(conflicts.length&&DATA.canon_lock_source)out.push({path:DATA.canon_lock_source,reason:'Machine-enforced canon-lock authority for explicit conflict.'});return unique(out,function(v){return v.path;});}
  function analyzeText(text,branch){var records=matchedRecords(text),locks=applicableLocks(records),conflicts=violations(text,locks),events=matchedEvents(text),mentions=observedMentions(records),derived=derivedSurfaces(records,events,conflicts),authority=authoritativeReview(records,events,conflicts);return {schema:'starsilk-revision-report/1',generated_at:new Date().toISOString(),branch:{id:branch.id,name:safeName(branch.name)},proposal:text,verdict:conflicts.length?'blocked-by-machine-lock':'human-decision-required',boundary:'Known blast radius only; this is not a complete canon impact claim.',summary:{recognized_records:records.length,applicable_locks:locks.length,hard_conflicts:conflicts.length,chronology_touchpoints:events.length,observed_mentions:mentions.length,authoritative_review_surfaces:authority.length,derived_review_surfaces:derived.length},recognized_records:records,applicable_locks:locks,conflicts:conflicts,chronology_touchpoints:events,observed_mentions:mentions,authoritative_review:authority,derived_review:derived,unknown_consequences:['The machine lock registry is an intentionally incomplete subset of Starsilk canon. No conflict does not mean canon-compatible.','Unstructured, source-local, contextual, thematic, and deliberately unknown consequences are not inferred by this chamber.','Observed cross-references prove mentions only. They are review touchpoints, not semantic relationships or causal dependencies.']};}

  function activeBranch(){return branches.find(function(b){return b.id===activeId;})||null;}
  function nextBranchName(){branchCounter+=1;var n=branchCounter,label='';while(n>0){n-=1;label=String.fromCharCode(65+(n%26))+label;n=Math.floor(n/26);}return 'Reality '+label;}
  function createBranch(text,name){var b={id:'reality-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),name:safeName(name||nextBranchName()),proposal:String(text||'').slice(0,300000),result:null};branches.push(b);activeId=b.id;renderAll();return b;}
  function syncFields(){var b=activeBranch();if(!b)return;b.name=safeName(branchName.value);b.proposal=proposal.value.slice(0,300000);}
  function selectBranch(id){syncFields();activeId=id;renderAll();proposal.focus();}
  function currentBaselineResult(){return {schema:'starsilk-revision-report/1',branch:{id:'current-canon',name:'Current Canon'},proposal:'',verdict:'immutable-baseline',summary:{recognized_records:0,applicable_locks:0,hard_conflicts:0,chronology_touchpoints:0,observed_mentions:0,authoritative_review_surfaces:0,derived_review_surfaces:0},recognized_records:[],applicable_locks:[],conflicts:[],chronology_touchpoints:[],observed_mentions:[],authoritative_review:[],derived_review:[],unknown_consequences:[]};}

  function renderBranches(){branchList.innerHTML='';branches.forEach(function(b){var button=document.createElement('button');button.type='button';button.className='revision-branch'+(b.id===activeId?' is-active':'');button.dataset.branchId=b.id;button.setAttribute('aria-pressed',String(b.id===activeId));button.innerHTML='<strong>'+esc(b.name)+'</strong><span>'+(b.result?(b.result.summary.hard_conflicts?b.result.summary.hard_conflicts+' hard conflict'+(b.result.summary.hard_conflicts===1?'':'s'):'analyzed'):'not analyzed')+'</span>';branchList.appendChild(button);});}
  function renderCompareOptions(){var previous=compareSelect.value;compareSelect.innerHTML='<option value="current-canon">Current Canon</option>';branches.forEach(function(b){if(b.id===activeId)return;var option=document.createElement('option');option.value=b.id;option.textContent=b.name;compareSelect.appendChild(option);});if(Array.from(compareSelect.options).some(function(o){return o.value===previous;}))compareSelect.value=previous;}
  function renderAll(){var b=activeBranch();if(!b){createBranch('',nextBranchName());return;}branchName.value=b.name;proposal.value=b.proposal;renderBranches();renderCompareOptions();if(b.result)renderConsequences(b.result,false);else consequences.innerHTML='<div class="revision-empty"><span class="eyebrow">Known blast radius</span><p>Analyze this speculative reality to map only the evidence the archive can prove is touched.</p></div>';comparison.hidden=true;deleteBtn.disabled=branches.length<=1;}

  function summaryMarkup(result){var s=result.summary,blocked=result.verdict==='blocked-by-machine-lock';return '<div class="revision-verdict '+(blocked?'is-blocked':'is-human')+'"><span class="eyebrow">Canonicalization status</span><strong>'+(blocked?'BLOCKED BY MACHINE LOCK':'HUMAN DECISION REQUIRED')+'</strong><p>'+(blocked?'At least one explicit applicable machine prohibition matched this proposal.':'No explicit machine prohibition matched. That is not permission to canonize it; the lock registry is only a subset of canon.')+'</p></div><div class="revision-counts"><span>Records <b>'+s.recognized_records+'</b></span><span>Hard conflicts <b>'+s.hard_conflicts+'</b></span><span>Chronology <b>'+s.chronology_touchpoints+'</b></span><span>Observed mentions <b>'+s.observed_mentions+'</b></span><span>Authority review <b>'+s.authoritative_review_surfaces+'</b></span><span>Derived review <b>'+s.derived_review_surfaces+'</b></span></div><p class="revision-blast-note">'+esc(result.boundary)+'</p>';}
  function listMarkup(title,items,formatter,empty){return '<section class="revision-impact-group"><h4>'+esc(title)+'</h4>'+(items.length?'<ul>'+items.map(function(item){return '<li>'+formatter(item)+'</li>';}).join('')+'</ul>':'<p class="revision-empty-line">'+esc(empty||'None established by this analysis.')+'</p>')+'</section>';}
  function renderConsequences(result,sacrificeMode){var html=summaryMarkup(result);if(sacrificeMode)html+='<div class="revision-sacrifice-banner"><span class="eyebrow">What would I have to sacrifice?</span><h3>These are the established surfaces you would have to reconsider.</h3><p>The chamber does not decide which one should lose. It refuses to hide the price.</p></div>';
    html+=listMarkup('Confirmed hard conflicts',result.conflicts,function(c){return '<span class="revision-conflict"><strong>'+esc(c.description)+'</strong><br><code>'+esc(c.lock_id)+'</code> · matched prohibition <code>'+esc(c.pattern)+'</code></span>';},'No explicit machine-lock conflict detected. Human review is still required.');
    html+=listMarkup('Authoritative surfaces to review',result.authoritative_review,function(v){return '<code>'+esc(v.path)+'</code><br><span>'+esc(v.reason)+'</span>';},'No authored source surface was mechanically matched.');
    html+=listMarkup('Chronology touchpoints',result.chronology_touchpoints,function(e){var t=e.temporal||{},bits=[t.exact_authored_marker,t.relative_marker,t.duration&&t.duration.authored_text].filter(Boolean).join(' · ');return '<strong>'+esc(e.label)+'</strong> <code>'+esc(e.event_id)+'</code>'+(bits?'<br><span>'+esc(bits)+'</span>':'');},'No authored chronology label or marker was mechanically matched.');
    html+=listMarkup('Observed mention touchpoints',result.observed_mentions,function(m){return '<strong>'+esc(m.source_title)+'</strong> → <strong>'+esc(m.target_title)+'</strong><br><span><code>mentions</code> / <code>observed-xref</code>'+(m.evidence_href?' · <a href="'+esc(m.evidence_href)+'">published evidence</a>':'')+'</span>';},'No incident observed-xref mention was found for the matched records.');
    html+=listMarkup('Derived surfaces to rebuild or review',result.derived_review,function(v){return '<a href="'+esc(v.path)+'">'+esc(v.path)+'</a><br><span>'+esc(v.reason)+'</span>';},'No deterministic derivative was mechanically identified.');
    html+=listMarkup('Unknown consequences',result.unknown_consequences,function(v){return esc(v);},'None.');consequences.innerHTML=html;}

  function analyzeActive(sacrificeMode){syncFields();var b=activeBranch(),text=b.proposal.trim();if(!text){announce('Write a proposed reality change before analyzing it.');proposal.focus();return;}if(text.length>300000){announce('Proposal is too large. Keep a reality under 300,000 characters.');return;}b.result=analyzeText(text,b);renderBranches();renderConsequences(b.result,!!sacrificeMode);comparison.hidden=true;announce(b.result.verdict==='blocked-by-machine-lock'?'Reality analyzed: BLOCKED BY MACHINE LOCK.':'Reality analyzed: HUMAN DECISION REQUIRED.');}

  function keySets(result){return {records:(result.recognized_records||[]).map(function(v){return v.stable_id;}),conflicts:(result.conflicts||[]).map(function(v){return v.lock_id;}),events:(result.chronology_touchpoints||[]).map(function(v){return v.event_id;}),mentions:(result.observed_mentions||[]).map(function(v){return v.source+' → '+v.target;}),derived:(result.derived_review||[]).map(function(v){return v.path;})};}
  function splitSets(a,b){var as=new Set(a),bs=new Set(b);return {a:a.filter(function(v){return !bs.has(v);}),shared:a.filter(function(v){return bs.has(v);}),b:b.filter(function(v){return !as.has(v);})};}
  function comparisonRow(label,sets,aName,bName){function cell(values){return values.length?'<ul>'+values.map(function(v){return '<li>'+esc(v)+'</li>';}).join('')+'</ul>':'<span class="revision-none">None</span>';}return '<section class="revision-compare-row"><h4>'+esc(label)+'</h4><div><article><span>'+esc(aName)+' only</span>'+cell(sets.a)+'</article><article><span>Shared</span>'+cell(sets.shared)+'</article><article><span>'+esc(bName)+' only</span>'+cell(sets.b)+'</article></div></section>';}
  function compareRealities(){syncFields();var a=activeBranch();if(!a)return;if(!a.result&&a.proposal.trim())a.result=analyzeText(a.proposal.trim(),a);if(!a.result){announce('Analyze or write the active reality before comparing it.');return;}var targetId=compareSelect.value,b,targetResult;if(targetId==='current-canon'){b={id:'current-canon',name:'Current Canon'};targetResult=currentBaselineResult();}else{b=branches.find(function(item){return item.id===targetId;});if(!b){announce('Choose a comparison reality.');return;}targetResult=b.result||(b.proposal.trim()?analyzeText(b.proposal.trim(),b):currentBaselineResult());}
    var ak=keySets(a.result),bk=keySets(targetResult),html='<header><span class="eyebrow">Reality diff</span><h3>'+esc(a.name)+' ↔ '+esc(b.name)+'</h3><p>Difference, not recommendation. Shared and divergent evidence footprints only.</p></header>';['records','conflicts','events','mentions','derived'].forEach(function(key){var label={records:'Matched records',conflicts:'Machine-lock conflicts',events:'Chronology touchpoints',mentions:'Observed mentions',derived:'Derived review surfaces'}[key];html+=comparisonRow(label,splitSets(ak[key],bk[key]),a.name,b.name);});comparison.innerHTML=html;comparison.hidden=false;comparison.scrollIntoView({block:'nearest'});announce('Reality comparison rendered. No branch was ranked or promoted.');}

  function packetText(result){var lines=['# Starsilk Revision Chamber Change Packet','','Reality: '+result.branch.name,'Status: '+(result.verdict==='blocked-by-machine-lock'?'BLOCKED BY MACHINE LOCK':'HUMAN DECISION REQUIRED'),result.boundary,'','## Proposed reality','',result.proposal,'','## Confirmed hard conflicts'];if(result.conflicts.length)result.conflicts.forEach(function(c){lines.push('- '+c.lock_id+': '+c.description+' — matched '+c.pattern);});else lines.push('- None detected by the machine-lock subset. This is not a compatibility verdict.');lines.push('','## Authoritative surfaces to review');result.authoritative_review.forEach(function(v){lines.push('- '+v.path+' — '+v.reason);});if(!result.authoritative_review.length)lines.push('- None mechanically matched.');lines.push('','## Chronology touchpoints');result.chronology_touchpoints.forEach(function(e){lines.push('- '+e.event_id+': '+e.label);});if(!result.chronology_touchpoints.length)lines.push('- None mechanically matched.');lines.push('','## Observed mention touchpoints');result.observed_mentions.forEach(function(m){lines.push('- '+m.source+' -> '+m.target+' [mentions / observed-xref]');});if(!result.observed_mentions.length)lines.push('- None mechanically matched.');lines.push('','## Derived surfaces to review');result.derived_review.forEach(function(v){lines.push('- '+v.path);});if(!result.derived_review.length)lines.push('- None mechanically identified.');lines.push('','## Unknown consequences');result.unknown_consequences.forEach(function(v){lines.push('- '+v);});lines.push('','No action in this packet changes canon. Fork -> inspect -> decide -> propagate is a human-controlled sequence.');return lines.join('\n');}
  function copyPacket(){var b=activeBranch();if(!b||!b.result){announce('Analyze the active reality before copying a change packet.');return;}var text=packetText(b.result);if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(text).then(function(){announce('Change packet copied.');}).catch(function(){announce('Clipboard copy was blocked by this browser.');});else announce('Clipboard access is unavailable in this browser.');}
  function download(name,payload){var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url);},0);}
  function exportBranch(){syncFields();var b=activeBranch();if(!b)return;download('starsilk-revision-'+b.id+'.json',{schema:'starsilk-revision-branch/1',name:b.name,proposal:b.proposal,result:b.result});announce('Active speculative reality exported.');}
  function exportWorkspace(){syncFields();download('starsilk-revision-workspace.json',{schema:'starsilk-revision-workspace/1',exported_at:new Date().toISOString(),branches:branches.map(function(b){return {name:b.name,proposal:b.proposal,result:b.result};})});announce('Speculative workspace exported. No canon state was included or changed.');}
  function importWorkspace(file){if(!file)return;if(file.size>4000000){announce('Workspace file is too large.');importInput.value='';return;}file.text().then(function(text){var data=JSON.parse(text),items=[];if(data.schema==='starsilk-revision-workspace/1'&&Array.isArray(data.branches))items=data.branches;else if(data.schema==='starsilk-revision-branch/1')items=[data];else throw new Error('schema');if(!items.length||items.length>12)throw new Error('count');var imported=[];items.forEach(function(item){var text=String(item.proposal||'');if(text.length>300000)throw new Error('proposal');branchCounter+=1;imported.push({id:'reality-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),name:safeName(item.name||nextBranchName()),proposal:text,result:null});});branches=imported;activeId=branches[0].id;renderAll();announce('Imported '+branches.length+' speculative realit'+(branches.length===1?'y':'ies')+'. Results will be recomputed from the current archive.');}).catch(function(){announce('That file is not a valid Revision Chamber workspace.');}).finally(function(){importInput.value='';});}
  function setOpen(open,focus){panel.hidden=!open;if(open){if(!activeBranch())createBranch('',nextBranchName());if(focus)proposal.focus();}else if(focus&&lastOpener&&typeof lastOpener.focus==='function')lastOpener.focus();}
  function openFromReader(){lastOpener=document.getElementById('readerWorkbenchToggle')||readerBridge;var readerClose=document.getElementById('readerWorkbenchClose');if(readerClose)readerClose.click();if(!activeBranch())createBranch('',nextBranchName());setOpen(true,true);}
  function openFromWitness(){lastOpener=document.getElementById('witnessEngineToggle')||witnessBridge;var witnessDraft=document.getElementById('witnessDraft'),text=witnessDraft?witnessDraft.value:'';var witnessClose=document.getElementById('witnessEngineClose');if(witnessClose)witnessClose.click();createBranch(text,nextBranchName());setOpen(true,true);announce(text.trim()?'Forked the Witness draft into a speculative reality. Nothing was canonized.':'Created a blank speculative reality.');}

  branchList.addEventListener('click',function(event){var button=event.target.closest('[data-branch-id]');if(button)selectBranch(button.dataset.branchId);});
  newBtn.addEventListener('click',function(){syncFields();createBranch('',nextBranchName());announce('New speculative reality forked in browser memory.');proposal.focus();});
  branchName.addEventListener('change',function(){syncFields();renderBranches();renderCompareOptions();});
  proposal.addEventListener('input',function(){var b=activeBranch();if(b){b.proposal=proposal.value.slice(0,300000);b.result=null;renderBranches();comparison.hidden=true;}});
  analyzeBtn.addEventListener('click',function(){analyzeActive(false);});
  sacrificeBtn.addEventListener('click',function(){analyzeActive(true);});
  duplicateBtn.addEventListener('click',function(){syncFields();var b=activeBranch();if(!b)return;createBranch(b.proposal,b.name+' — fork');announce('Reality duplicated. The fork is independent and still speculative.');});
  deleteBtn.addEventListener('click',function(){if(branches.length<=1){announce('Keep at least one speculative reality in the chamber.');return;}var index=branches.findIndex(function(b){return b.id===activeId;});branches=branches.filter(function(b){return b.id!==activeId;});activeId=branches[Math.max(0,index-1)].id;renderAll();announce('Speculative reality discarded. Canon was never touched.');});
  compareBtn.addEventListener('click',compareRealities);
  copyPacketBtn.addEventListener('click',copyPacket);
  exportBranchBtn.addEventListener('click',exportBranch);
  exportWorkspaceBtn.addEventListener('click',exportWorkspace);
  importInput.addEventListener('change',function(){importWorkspace(importInput.files&&importInput.files[0]);});
  close.addEventListener('click',function(){syncFields();setOpen(false,true);});
  if(readerBridge)readerBridge.addEventListener('click',openFromReader);
  if(witnessBridge)witnessBridge.addEventListener('click',openFromWitness);
  document.addEventListener('keydown',function(event){if(event.key==='Escape'&&!panel.hidden){event.preventDefault();syncFields();setOpen(false,true);return;}if((event.ctrlKey||event.metaKey)&&event.shiftKey&&event.key.toLowerCase()==='r'){event.preventDefault();lastOpener=document.getElementById('readerWorkbenchToggle')||readerBridge||close;if(panel.hidden){if(!activeBranch())createBranch('',nextBranchName());setOpen(true,true);}else setOpen(false,true);}});

  createBranch('',nextBranchName());
})();
