/* Starsilk Truth Lab: source-backed analysis suite; zero canon authority. */
(function(){
  'use strict';
  var DATA=window.STARSILK_REVISION_DATA||{events:[],records:[]};
  var panel,reader,launcher,activeTab='parallax',parallaxAssignments=Object.create(null);
  var perspectiveLabels=['UNASSIGNED','WORLD EVIDENCE','CODEC','ADMINISTRATION','SURVIVOR / WITNESS','LATER INTERPRETATION'];
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function slug(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
  function tokens(v){var stop=new Set(['the','and','that','this','with','from','into','over','under','through','after','before','only','does','have','has','had','was','were','are','for','its','his','her','their','they','them','then','than','not','but','can','will','would','should','could','about','within','without']);return slug(v).split(/\s+/).filter(function(x){return x.length>=3&&!stop.has(x);});}
  function overlap(a,b){var A=new Set(tokens(a)),seen=new Set(),n=0;tokens(b).forEach(function(x){if(A.has(x)&&!seen.has(x)){seen.add(x);n++;}});return n;}
  function literalRegex(value){return new RegExp('(^|[^A-Za-z0-9])'+String(value).replace(/[.*+?^${}()|[\\]\\\\]/g,'\\\\$&')+'(?=$|[^A-Za-z0-9])','i');}
  function wordMatch(text,value){if(!value||String(value).trim().length<2)return false;return literalRegex(String(value).trim()).test(String(text||''));}
  function recordAliases(record){var out=[record.stable_id,String(record.stable_id||'').replace(/-/g,' '),record.title];(record.aliases||[]).forEach(function(v){out.push(v);});return out.filter(Boolean);}
  function matchedRecords(text){return (DATA.records||[]).filter(function(record){return recordAliases(record).some(function(alias){return wordMatch(text,alias);});});}
  function eventAliases(event){var temporal=event.temporal||{},out=[event.event_id,String(event.event_id||'').replace(/-/g,' '),event.label,temporal.exact_authored_marker,temporal.relative_marker];if(temporal.duration&&temporal.duration.authored_text)out.push(temporal.duration.authored_text);return out.filter(Boolean);}
  function matchedEvents(text){return events().filter(function(event){return eventAliases(event).some(function(alias){return wordMatch(text,alias);});});}
  function applicableLocks(records){var ids=records.map(function(r){return r.stable_id;});return (DATA.locks||[]).filter(function(lock){return lock.scope==='document'||(lock.target_stable_id&&ids.indexOf(lock.target_stable_id)!==-1);});}
  function safeRegex(pattern){try{pattern=String(pattern||'');if(pattern.indexOf('(?i)')===0)pattern=pattern.slice(4);return new RegExp(pattern,'i');}catch(error){return null;}}
  function lockViolations(text,locks){var out=[];locks.forEach(function(lock){(lock.prohibitions||[]).forEach(function(pattern){var re=safeRegex(pattern);if(re&&re.test(text))out.push({lock_id:lock.lock_id,description:lock.description,scope:lock.scope,target_stable_id:lock.target_stable_id||null,pattern:pattern});});});var seen=new Set();return out.filter(function(v){var k=v.lock_id+'|'+v.pattern;if(seen.has(k))return false;seen.add(k);return true;});}
  function proposalNumerics(text){var out=[],re=/\b(\d[\d,]*(?:\.\d+)?)\s*(thousand|million|billion)?\b/gi,m,scale={thousand:1000,million:1000000,billion:1000000000};while((m=re.exec(text))){var value=parseFloat(m[1].replace(/,/g,''));if(m[2])value*=scale[m[2].toLowerCase()];if(Number.isFinite(value))out.push(value);}return Array.from(new Set(out));}
  function sourceContradictions(text,matchedClaims){var proposed=proposalNumerics(text),changeCue=/\b(replace|instead|change|changed|retcon|rewrite|becomes?|became|now|rather|not|only|was|were|is|are|lasted|count|confirmed|survival)\b/i,out=[];if(!proposed.length)return out;matchedClaims.forEach(function(claim){if(overlap(text,claim.label)<2&&!wordMatch(text,claim.claim_id))return;var facts=((DATA.claim_numeric_facts||{})[claim.claim_id]||[]).map(Number).filter(Number.isFinite);if(!facts.length)return;var matching=proposed.filter(function(v){return facts.some(function(f){return Math.abs(f-v)<1e-9;});}),differing=proposed.filter(function(v){return !facts.some(function(f){return Math.abs(f-v)<1e-9;});});if(differing.length&&(matching.length===0||changeCue.test(text)))out.push({claim_id:claim.claim_id,label:claim.label,source_ref:claim.source_ref,source_locator:claim.source_locator,evidence_class:'explicit-numeric-mismatch',authored_values:Array.from(new Set(facts)),proposed_values:differing});});var seen=new Set();return out.filter(function(v){if(seen.has(v.claim_id))return false;seen.add(v.claim_id);return true;});}
  function reviewSurfaces(records,evs,locks,matchedClaims){var out=[];records.forEach(function(r){var id=r.stable_id;out.push('entities/'+id+'/','discover/packets/'+id+'.json','machine/entities/'+id+'.json','machine/entities/'+id+'.md','relationships/#entity-'+id);});evs.forEach(function(e){out.push('chronology/#event-'+e.event_id);});if(matchedClaims.length)out.push('entities/canon-ledger/','discover/packets/canon-ledger.json');if(locks.length)out.push('canon/');return Array.from(new Set(out));}
  function claims(){var out=[];document.querySelectorAll('#canon-ledger [data-lore-record]').forEach(function(article){var id=article.getAttribute('data-lore-record'),group=article.closest('.lore-group'),h3=group&&group.querySelector('h3'),tag=article.querySelector('.lore-tag'),h4=article.querySelector('h4'),p=article.querySelector('p'),refs=[];article.querySelectorAll('a.xref-link[href^="#"]').forEach(function(a){var h=a.getAttribute('href')||'';if(h.length>1)refs.push(h.slice(1));});out.push({claim_id:id,order:Number(String(id).slice(1))||0,domain:h3?h3.textContent.replace(/\s+/g,' ').trim():'',tag:tag?tag.textContent.replace(/\s+/g,' ').trim():'',label:h4?h4.textContent.replace(/\s+/g,' ').trim():id,statement:p?p.textContent.replace(/\s+/g,' ').trim():'',source_ref:'src/content/sections/canon-ledger.body.html',source_locator:'data-lore-record="'+id+'"',entity_stable_ids:Array.from(new Set(refs))});});return out;}
  function events(){return Array.isArray(DATA.events)?DATA.events:[];}
  function phaseOf(e){var h=String(e.source_heading||'');var m=h.match(/Phase\s+([IVX]+)/i);if(!m)return null;return {I:1,II:2,III:3,IV:4,V:5}[m[1].toUpperCase()]||null;}
  function markerYear(e){var m=String((e.temporal||{}).exact_authored_marker||'').match(/Year(?:s)?\s+(\d+)/i);return m?Number(m[1]):null;}
  function download(name,text,type){var blob=new Blob([text],{type:type||'text/plain;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(u);},0);}
  function announce(msg){var s=document.getElementById('truthLabStatus');if(s)s.textContent=msg;}
  function ensureCss(){if(document.querySelector('link[data-truth-lab-style]'))return;var l=document.createElement('link');l.rel='stylesheet';l.href='truth-lab.css';l.dataset.truthLabStyle='true';document.head.appendChild(l);}
  function buildPanel(){
    if(document.getElementById('truthLab'))return document.getElementById('truthLab');
    var a=document.createElement('aside');a.id='truthLab';a.className='truth-lab';a.hidden=true;a.setAttribute('aria-labelledby','truthLabHeading');
    a.innerHTML='<header class="truth-head"><div><span class="eyebrow">Epistemic analysis suite</span><h2 id="truthLabHeading">Truth Lab</h2></div><button type="button" id="truthLabClose">Close</button></header>'
      +'<p class="truth-boundary"><strong>Evidence tools, not canon authority.</strong> Every result is derived from authored Canon Loom claims, authored chronology metadata, stable record identities, and explicit repository boundaries. Local classifications never persist, never write the repository, and never turn missing evidence into fact.</p>'
      +'<div id="truthLabStatus" class="truth-status" role="status" aria-live="polite"></div>'
      +'<nav class="truth-tabs" aria-label="Truth Lab tools"><button data-truth-tab="parallax">Parallax Engine</button><button data-truth-tab="horizon">Truth Horizon</button><button data-truth-tab="silence">Silence Index</button><button data-truth-tab="quarry">Canon Quarry</button><button data-truth-tab="receipt">Canon Change Receipt</button></nav>'
      +'<div id="truthLabBody"></div>';
    document.body.appendChild(a);return a;
  }
  function ensureLauncher(){var actions=document.querySelector('.reader-workbench-head-actions');if(!actions)return null;launcher=document.getElementById('readerToTruthLab');if(!launcher){launcher=document.createElement('button');launcher.type='button';launcher.id='readerToTruthLab';launcher.textContent='Truth Lab';var close=document.getElementById('readerWorkbenchClose');actions.insertBefore(launcher,close||null);}return launcher;}
  function renderTabs(){panel.querySelectorAll('[data-truth-tab]').forEach(function(b){b.classList.toggle('is-active',b.dataset.truthTab===activeTab);b.setAttribute('aria-pressed',String(b.dataset.truthTab===activeTab));});}
  function render(){renderTabs();({parallax:renderParallax,horizon:renderHorizon,silence:renderSilence,quarry:renderQuarry,receipt:renderReceipt}[activeTab]||renderParallax)();}
  function perspectiveSelect(id){return '<select data-perspective="'+esc(id)+'" aria-label="Local perspective assignment for '+esc(id)+'">'+perspectiveLabels.map(function(v){return '<option'+((parallaxAssignments[id]||'UNASSIGNED')===v?' selected':'')+'>'+esc(v)+'</option>';}).join('')+'</select>';}
  function parallaxMatches(q){var needle=slug(q);if(!needle)return claims().slice(0,18);return claims().filter(function(c){return slug(c.claim_id+' '+c.domain+' '+c.tag+' '+c.label+' '+c.statement+' '+c.entity_stable_ids.join(' ')).indexOf(needle)>=0;}).slice(0,40);}
  function renderParallax(){
    var body=document.getElementById('truthLabBody'),q=body.dataset.parallaxQuery||'First Dirt',matches=parallaxMatches(q);
    body.innerHTML='<section class="truth-tool"><div class="truth-tool-head"><div><span class="eyebrow">01 / Multi-perspective evidence</span><h3>Parallax Engine</h3></div><p>Find authored claims, then assign a local reading perspective. The assignment is deliberately <em>not</em> treated as authored speaker metadata.</p></div>'
      +'<label class="truth-field"><span>Evidence query</span><input id="parallaxQuery" value="'+esc(q)+'" autocomplete="off" placeholder="First Dirt, Blood Ring, Codec…"></label>'
      +'<div class="truth-parallax-grid">'+perspectiveLabels.map(function(label){var items=matches.filter(function(c){return (parallaxAssignments[c.claim_id]||'UNASSIGNED')===label;});if(label!=='UNASSIGNED'&&!items.length)return '';return '<section class="truth-column"><header><span>'+esc(label)+'</span><b>'+items.length+'</b></header><div>'+items.map(function(c){return '<article class="truth-claim"><code>'+c.claim_id+'</code><strong>'+esc(c.label)+'</strong><p>'+esc(c.statement)+'</p><dl class="truth-mini-proof"><div><dt>Evidence authority</dt><dd>authored-source</dd></div><div><dt>Evidence class</dt><dd>authored-lore-record</dd></div><div><dt>Canon-lock status</dt><dd>UNKNOWN · not inferred</dd></div><div><dt>Temporal scope</dt><dd>UNKNOWN · not structurally authored per claim</dd></div><div><dt>Contradiction relation</dt><dd>UNKNOWN · no semantic relation inferred</dd></div></dl>'+perspectiveSelect(c.claim_id)+'<small>'+esc(c.source_ref)+' · '+esc(c.source_locator)+'</small></article>';}).join('')+(items.length?'':'<p class="truth-empty">No locally assigned evidence.</p>')+'</div></section>';}).join('')+'</div>'
      +'<p class="truth-note">Columns exist only for evidence currently present in the result set. Perspective placement is browser-memory analysis, zero canon authority.</p></section>';
    var input=document.getElementById('parallaxQuery');input.addEventListener('input',function(){body.dataset.parallaxQuery=input.value.slice(0,100);renderParallax();});
    body.querySelectorAll('[data-perspective]').forEach(function(s){s.addEventListener('change',function(){parallaxAssignments[s.dataset.perspective]=s.value;renderParallax();announce('Local perspective assignment changed. Canon unchanged.');});});
  }
  function horizonStatus(e,h){var pe=phaseOf(e),ph=phaseOf(h),ye=markerYear(e),yh=markerYear(h);if(e.event_id===h.event_id)return ['HORIZON EVENT','current'];if(pe&&ph&&pe<ph)return ['ESTABLISHED BY PHASE ORDER','past'];if(pe&&ph&&pe>ph)return ['NOT YET ESTABLISHED','future'];if(pe===ph&&ye!=null&&yh!=null){if(ye<yh)return ['ESTABLISHED BY AUTHORED YEAR','past'];if(ye>yh)return ['NOT YET ESTABLISHED','future'];}return ['UNKNOWN WITHIN HORIZON','unknown'];}
  function renderHorizon(){
    var body=document.getElementById('truthLabBody'),es=events(),chosen=body.dataset.horizonId||((es.find(function(e){return e.event_id==='siege-ruby-eclipse';})||es[0]||{}).event_id||''),h=es.find(function(e){return e.event_id===chosen;})||es[0];
    body.innerHTML='<section class="truth-tool"><div class="truth-tool-head"><div><span class="eyebrow">02 / Temporal knowledge boundary</span><h3>Truth Horizon</h3></div><p>Move an archive horizon through the authored phase structure. This is not a claim about what any character personally knew.</p></div>'
      +'<label class="truth-field"><span>Archive horizon</span><select id="truthHorizonSelect">'+es.map(function(e){var t=e.temporal||{},m=t.exact_authored_marker||t.relative_marker||'time unknown';return '<option value="'+esc(e.event_id)+'"'+(e.event_id===chosen?' selected':'')+'>'+esc(e.label+' · '+m)+'</option>';}).join('')+'</select></label>'
      +'<div class="truth-horizon-list">'+es.map(function(e){var st=horizonStatus(e,h),t=e.temporal||{},m=t.exact_authored_marker||t.relative_marker||(t.duration&&t.duration.authored_text)||'temporal marker unknown';return '<article class="truth-event is-'+st[1]+'" data-event-id="'+esc(e.event_id)+'"><span>'+esc(st[0])+'</span><strong>'+esc(e.label)+'</strong><code>'+esc(m)+'</code><small>'+esc(e.source_heading||'')+'</small></article>';}).join('')+'</div>'
      +'<p class="truth-note">Only authored phase order and directly authored temporal markers participate. Same-phase events without comparable markers remain UNKNOWN. SUPERSEDED, RETROSPECTIVE, and other stronger temporal semantics remain unavailable unless a source explicitly authors them.</p></section>';
    document.getElementById('truthHorizonSelect').addEventListener('change',function(e){body.dataset.horizonId=e.target.value;renderHorizon();});
  }
  function silenceEntries(){
    var out=[],body=document.getElementById('truthLabBody'),horizonId=body&&body.dataset.horizonId,h=events().find(function(e){return e.event_id===horizonId;});events().forEach(function(e){var t=e.temporal||{},marker=t.exact_authored_marker||t.relative_marker||(t.duration&&t.duration.authored_text);if(t.certainty!=='unknown'&&marker)out.push({kind:'KNOWN TEMPORAL MARKER',subject:e.label,evidence:'The chronology source explicitly authors: '+marker+'.',source:e.event_id});if(t.certainty==='unknown')out.push({kind:'UNKNOWN TIME',subject:e.label,evidence:'Chronology source marks temporal certainty as unknown.',source:e.event_id});if(t.certainty==='unknown'&&!t.exact_authored_marker&&!t.relative_marker&&!t.duration)out.push({kind:'RELATIVE PLACEMENT UNAUTHORED',subject:e.label,evidence:'No authored marker or duration is present for this event.',source:e.event_id});if(h&&horizonStatus(e,h)[1]==='future')out.push({kind:'NOT YET ESTABLISHED AT SELECTED HORIZON',subject:e.label,evidence:'Authored phase/year evidence places this event after the selected archive horizon. This is not a claim about character knowledge.',source:e.event_id});});
    out.push({kind:'DISPUTED / MULTIPLE SOURCES',subject:'Structured dispute state',evidence:'No general machine-readable dispute relation is authored for Canon Loom claims. The Lab leaves this unavailable rather than fabricating one.',source:'evidence-model boundary'});
    out.push({kind:'FORBIDDEN INFERENCE',subject:'Observed cross-reference',evidence:'A rendered xref proves mentions/reference only; it does not prove stronger relationship semantics.',source:'relationship boundary'});
    out.push({kind:'FORBIDDEN INFERENCE',subject:'Canon Ledger order',evidence:'Claim order is evidence order, not guaranteed chronology.',source:'Canon Loom boundary'});
    out.push({kind:'FORBIDDEN INFERENCE',subject:'Missing machine lock',evidence:'Absence of a machine lock is not permission, compatibility, falsity, or non-canon status.',source:'Revision Chamber boundary'});
    return out;
  }
  function renderSilence(){
    var body=document.getElementById('truthLabBody'),q=body.dataset.silenceQuery||'',all=silenceEntries(),list=q?all.filter(function(x){return slug(x.kind+' '+x.subject+' '+x.evidence).indexOf(slug(q))>=0;}):all;
    body.innerHTML='<section class="truth-tool"><div class="truth-tool-head"><div><span class="eyebrow">03 / Closed-world unknowns</span><h3>The Silence Index</h3></div><p>What the current structured evidence refuses to let the interface pretend to know.</p></div>'
      +'<label class="truth-field"><span>Filter silence</span><input id="silenceQuery" value="'+esc(q)+'" placeholder="time, relationship, lock…"></label>'
      +'<div class="truth-silence-list">'+list.map(function(x){return '<article><span>'+esc(x.kind)+'</span><strong>'+esc(x.subject)+'</strong><p>'+esc(x.evidence)+'</p><code>'+esc(x.source)+'</code></article>';}).join('')+'</div>'
      +'<p class="truth-note">Silence is reported only when an explicit unknown or inference boundary can be demonstrated. The Lab does not manufacture mystery from ordinary absence.</p></section>';
    document.getElementById('silenceQuery').addEventListener('input',function(e){body.dataset.silenceQuery=e.target.value.slice(0,100);renderSilence();});
  }
  function matchSentence(s){return claims().map(function(c){return {claim:c,score:overlap(s,c.label+' '+c.statement+' '+c.tag)};}).filter(function(x){return x.score>=2;}).sort(function(a,b){return b.score-a.score||a.claim.order-b.claim.order;}).slice(0,3);}
  function quarryPacket(text){
    var sentences=String(text||'').split(/(?<=[.!?])\s+|\n+/).map(function(s){return s.trim();}).filter(function(s){return s.length>=12;}).slice(0,80);
    var candidates=sentences.map(function(s,i){return {candidate_id:'Q'+String(i+1).padStart(3,'0'),statement:s,evidence_neighbors:matchSentence(s).map(function(m){return {claim_id:m.claim.claim_id,label:m.claim.label,statement:m.claim.statement,source_ref:m.claim.source_ref,source_locator:m.claim.source_locator,authority:'authored-source',evidence_class:'authored-lore-record',overlap_score:m.score};})};});
    var claimMap={},records=matchedRecords(text),evs=matchedEvents(text),locks=applicableLocks(records),hard=lockViolations(text,locks);
    candidates.forEach(function(c){c.evidence_neighbors.forEach(function(e){claimMap[e.claim_id]=claims().find(function(x){return x.claim_id===e.claim_id;})||e;});});
    var touchedClaims=Object.keys(claimMap).map(function(id){return claimMap[id];}),sourceConflicts=sourceContradictions(text,touchedClaims),unresolved=candidates.filter(function(c){return !c.evidence_neighbors.length;}).map(function(c){return {candidate_id:c.candidate_id,statement:c.statement,status:'UNKNOWN / SOURCE-LOCAL'};});
    return {schema:'starsilk-canon-quarry/2',generated_at:new Date().toISOString(),authority:'exploratory',boundary:'Candidate extraction only. Evidence neighbors and review touchpoints are mechanically sourced, not proof of equivalence, truth, contradiction, chronology, or canon status.',source_text:text,candidates:candidates,recognized_records:records.map(function(r){return {stable_id:r.stable_id,title:r.title,source_ref:r.source_ref};}),supporting_claim_ids:touchedClaims.map(function(c){return c.claim_id;}),chronology_touchpoints:evs,machine_lock_review:locks.map(function(l){return {lock_id:l.lock_id,scope:l.scope,target_stable_id:l.target_stable_id||null,description:l.description};}),machine_lock_conflicts:hard,possible_source_contradictions:sourceConflicts,unresolved_assertions:unresolved,review_surfaces:reviewSurfaces(records,evs,locks,touchedClaims),unknowns:['Unmatched source-local context is not inferred.','Lexical overlap is not semantic equivalence.','A machine-lock review item is not a lock violation unless it appears in machine_lock_conflicts.','No semantic contradiction is inferred; possible_source_contradictions contains only explicit numeric mismatch evidence.','No candidate is promoted into canon by this packet.']};
  }
  function quarryMarkdown(p){var lines=['# Starsilk Canon Quarry','','Status: EXPLORATORY','',p.boundary,''];p.candidates.forEach(function(c){lines.push('## '+c.candidate_id,'',c.statement,'','Evidence neighbors:');if(c.evidence_neighbors.length)c.evidence_neighbors.forEach(function(e){lines.push('- '+e.claim_id+' · '+e.label+' · '+e.source_locator);});else lines.push('- None mechanically matched. UNKNOWN / SOURCE-LOCAL.');lines.push('');});lines.push('## Recognized records','');(p.recognized_records.length?p.recognized_records:[{stable_id:'None mechanically matched',title:''}]).forEach(function(r){lines.push('- '+r.stable_id+(r.title?' · '+r.title:''));});lines.push('','## Chronology touchpoints');(p.chronology_touchpoints.length?p.chronology_touchpoints:[{event_id:'None mechanically matched',label:''}]).forEach(function(e){lines.push('- '+e.event_id+(e.label?' · '+e.label:''));});lines.push('','## Machine-lock review');(p.machine_lock_review.length?p.machine_lock_review:[{lock_id:'None mechanically matched',description:''}]).forEach(function(l){lines.push('- '+l.lock_id+(l.description?' · '+l.description:''));});lines.push('','## Possible source contradictions');(p.possible_source_contradictions.length?p.possible_source_contradictions:[{claim_id:'None proven',label:''}]).forEach(function(c){lines.push('- '+c.claim_id+(c.label?' · '+c.label:''));});lines.push('','## Unresolved assertions');(p.unresolved_assertions.length?p.unresolved_assertions:[{candidate_id:'None',statement:''}]).forEach(function(u){lines.push('- '+u.candidate_id+(u.statement?' · '+u.statement:''));});lines.push('','## Review surfaces');(p.review_surfaces.length?p.review_surfaces:['None mechanically identified']).forEach(function(x){lines.push('- '+x);});lines.push('','## Unknowns');p.unknowns.forEach(function(x){lines.push('- '+x);});return lines.join('\n');}
  function renderQuarry(){
    var body=document.getElementById('truthLabBody'),text=body.dataset.quarryText||'',p=quarryPacket(text);
    body.innerHTML='<section class="truth-tool"><div class="truth-tool-head"><div><span class="eyebrow">04 / Candidate extraction</span><h3>Canon Quarry</h3></div><p>Break new lore into candidate propositions, then expose the evidence, entities, chronology, locks, contradictions, review surfaces, and unresolved assertions the archive can actually support.</p></div>'
      +'<label class="truth-field"><span>Source text</span><textarea id="quarryText" placeholder="Paste canon-clean prose, a story passage, song notes, or a lore update…">'+esc(text)+'</textarea></label><div class="truth-actions"><label class="truth-file-label" for="quarryFile">Import text<input id="quarryFile" type="file" accept=".txt,.md,text/plain,text/markdown"></label><button id="quarryAnalyze">Extract candidates</button><button id="quarryJson">Export JSON</button><button id="quarryMd">Export Markdown</button></div>'
      +'<div class="truth-evidence-summary"><article><span>Known entities</span><b>'+p.recognized_records.length+'</b><small>'+esc(p.recognized_records.map(function(r){return r.stable_id;}).join(', ')||'none mechanically matched')+'</small></article><article><span>Chronology touchpoints</span><b>'+p.chronology_touchpoints.length+'</b><small>'+esc(p.chronology_touchpoints.map(function(e){return e.event_id;}).join(', ')||'none mechanically matched')+'</small></article><article><span>Machine-lock review</span><b>'+p.machine_lock_review.length+'</b><small>'+p.machine_lock_conflicts.length+' explicit conflict(s)</small></article><article><span>Unresolved assertions</span><b>'+p.unresolved_assertions.length+'</b><small>preserved as UNKNOWN / SOURCE-LOCAL</small></article></div>'
      +'<div class="truth-quarry-results">'+(text?p.candidates.map(function(c){return '<article><code>'+c.candidate_id+'</code><strong>'+esc(c.statement)+'</strong><div>'+((c.evidence_neighbors.length?c.evidence_neighbors.map(function(e){return '<p><code>'+e.claim_id+'</code> '+esc(e.label)+' <small>authored-source · authored-lore-record · overlap '+e.overlap_score+'</small></p>';}).join(''):'<p class="truth-empty">No mechanical evidence neighbor. UNKNOWN / SOURCE-LOCAL.</p>'))+'</div></article>';}).join(''):'<p class="truth-empty">Nothing quarried yet.</p>')+'</div><p class="truth-note">'+esc(p.boundary)+'</p></section>';
    var ta=document.getElementById('quarryText'),file=document.getElementById('quarryFile');file.addEventListener('change',function(){var f=file.files&&file.files[0];if(!f)return;f.text().then(function(v){body.dataset.quarryText=v.slice(0,300000);renderQuarry();announce('Local source file loaded. Nothing was canonized.');}).catch(function(){announce('Could not read that local text file.');});});document.getElementById('quarryAnalyze').addEventListener('click',function(){body.dataset.quarryText=ta.value.slice(0,300000);renderQuarry();announce('Candidate extraction rebuilt. Nothing was canonized.');});document.getElementById('quarryJson').addEventListener('click',function(){var x=quarryPacket(ta.value);download('starsilk-canon-quarry.json',JSON.stringify(x,null,2),'application/json');});document.getElementById('quarryMd').addEventListener('click',function(){var x=quarryPacket(ta.value);download('starsilk-canon-quarry.md',quarryMarkdown(x),'text/markdown;charset=utf-8');});
  }
  function sentenceSet(text){return Array.from(new Set(String(text||'').split(/(?<=[.!?])\s+|\n+/).map(function(s){return s.trim();}).filter(Boolean)));}
  function footprint(text){var cs=claims(),matched=cs.map(function(c){return {c:c,n:overlap(text,c.label+' '+c.statement+' '+c.tag)};}).filter(function(x){return x.n>=2||wordMatch(text,x.c.claim_id);}).sort(function(a,b){return b.n-a.n||a.c.order-b.c.order;}).slice(0,18).map(function(x){return x.c;}),records=matchedRecords(text),evs=matchedEvents(text),locks=applicableLocks(records),conflicts=lockViolations(text,locks),sourceConflicts=sourceContradictions(text,matched);return {claims:matched,records:records,events:evs,locks:locks,lock_conflicts:conflicts,source_contradictions:sourceConflicts,surfaces:reviewSurfaces(records,evs,locks,matched)};}
  function receipt(before,after){var a=sentenceSet(before),b=sentenceSet(after),removed=a.filter(function(x){return b.indexOf(x)<0;}),added=b.filter(function(x){return a.indexOf(x)<0;}),fa=footprint(before),fb=footprint(after),surfaces=Array.from(new Set(fa.surfaces.concat(fb.surfaces))),sources=[];fa.records.concat(fb.records).forEach(function(r){if(r.source_ref)sources.push(r.source_ref);});if(fa.claims.length||fb.claims.length)sources.push(DATA.claim_source||'src/content/sections/canon-ledger.body.html');if(fa.events.length||fb.events.length)sources.push(DATA.chronology_source||'src/chronology/events.json');if(fa.locks.length||fb.locks.length)sources.push(DATA.canon_lock_source||'src/canon/invariants.json');return {schema:'starsilk-canon-change-receipt/2',generated_at:new Date().toISOString(),authority:'exploratory',boundary:'Review receipt only. The listed authority and derivative surfaces are a provable subset derived from matched structured evidence, not a complete dependency graph and not proof of causation.',changes:{removed:removed,added:added},before:{claim_ids:fa.claims.map(function(c){return c.claim_id;}),record_ids:fa.records.map(function(r){return r.stable_id;}),event_ids:fa.events.map(function(e){return e.event_id;}),lock_ids:fa.locks.map(function(l){return l.lock_id;}),machine_lock_conflicts:fa.lock_conflicts,possible_source_contradictions:fa.source_contradictions},after:{claim_ids:fb.claims.map(function(c){return c.claim_id;}),record_ids:fb.records.map(function(r){return r.stable_id;}),event_ids:fb.events.map(function(e){return e.event_id;}),lock_ids:fb.locks.map(function(l){return l.lock_id;}),machine_lock_conflicts:fb.lock_conflicts,possible_source_contradictions:fb.source_contradictions},authoritative_review:Array.from(new Set(sources)),review_surfaces:surfaces,regeneration_review:surfaces.filter(function(x){return /discover\/packets|machine\/entities|chronology\//.test(x);}),unknowns:['Unstructured downstream consequences may exist outside the structured evidence set.','Observed xrefs remain mentions only.','A changed lock touchpoint is not itself proof of a lock violation.','A review surface is not a causal dependency.','No receipt mutates canon, generated output, or repository state.']};}
  function receiptMarkdown(r){var lines=['# Starsilk Canon Change Receipt','','Status: EXPLORATORY','',r.boundary,'','## Removed propositions'];(r.changes.removed.length?r.changes.removed:['None']).forEach(function(x){lines.push('- '+x);});lines.push('','## Added propositions');(r.changes.added.length?r.changes.added:['None']).forEach(function(x){lines.push('- '+x);});lines.push('','## Before evidence footprint','Claims: '+(r.before.claim_ids.join(', ')||'none'),'Records: '+(r.before.record_ids.join(', ')||'none'),'Events: '+(r.before.event_ids.join(', ')||'none'),'Locks: '+(r.before.lock_ids.join(', ')||'none'),'','## After evidence footprint','Claims: '+(r.after.claim_ids.join(', ')||'none'),'Records: '+(r.after.record_ids.join(', ')||'none'),'Events: '+(r.after.event_ids.join(', ')||'none'),'Locks: '+(r.after.lock_ids.join(', ')||'none'),'','## Authoritative review');(r.authoritative_review.length?r.authoritative_review:['None mechanically identified']).forEach(function(x){lines.push('- '+x);});lines.push('','## Derivative review surfaces');(r.review_surfaces.length?r.review_surfaces:['None mechanically identified']).forEach(function(x){lines.push('- '+x);});lines.push('','## Regeneration review');(r.regeneration_review.length?r.regeneration_review:['None mechanically identified']).forEach(function(x){lines.push('- '+x);});lines.push('','## Unknowns');r.unknowns.forEach(function(x){lines.push('- '+x);});return lines.join('\n');}
  function renderReceipt(){
    var body=document.getElementById('truthLabBody'),before=body.dataset.receiptBefore||'',after=body.dataset.receiptAfter||'',r=receipt(before,after);
    body.innerHTML='<section class="truth-tool"><div class="truth-tool-head"><div><span class="eyebrow">05 / Change proof</span><h3>Canon Change Receipt</h3></div><p>Compare two proposed text states and emit a source-aware review receipt without pretending the archive knows the complete blast radius.</p></div><div class="truth-receipt-inputs"><label class="truth-field"><span>Before</span><textarea id="receiptBefore">'+esc(before)+'</textarea></label><label class="truth-field"><span>After</span><textarea id="receiptAfter">'+esc(after)+'</textarea></label></div><div class="truth-actions"><button id="receiptBuild">Build receipt</button><button id="receiptJson">Export JSON</button><button id="receiptMd">Export Markdown</button></div>'
      +'<div class="truth-receipt-grid"><section><span class="eyebrow">Removed</span>'+(r.changes.removed.map(function(x){return '<p>'+esc(x)+'</p>';}).join('')||'<p class="truth-empty">None.</p>')+'</section><section><span class="eyebrow">Added</span>'+(r.changes.added.map(function(x){return '<p>'+esc(x)+'</p>';}).join('')||'<p class="truth-empty">None.</p>')+'</section><section><span class="eyebrow">Authoritative review</span>'+(r.authoritative_review.map(function(x){return '<code>'+esc(x)+'</code>';}).join('')||'<p class="truth-empty">None mechanically identified.</p>')+'</section><section><span class="eyebrow">Derivative review surfaces</span>'+(r.review_surfaces.map(function(x){return '<code>'+esc(x)+'</code>';}).join('')||'<p class="truth-empty">None mechanically identified.</p>')+'</section><section><span class="eyebrow">Regeneration review</span>'+(r.regeneration_review.map(function(x){return '<code>'+esc(x)+'</code>';}).join('')||'<p class="truth-empty">None mechanically identified.</p>')+'</section><section><span class="eyebrow">Evidence delta</span><p>Claims '+r.before.claim_ids.length+' → '+r.after.claim_ids.length+'</p><p>Records '+r.before.record_ids.length+' → '+r.after.record_ids.length+'</p><p>Events '+r.before.event_ids.length+' → '+r.after.event_ids.length+'</p><p>Locks '+r.before.lock_ids.length+' → '+r.after.lock_ids.length+'</p></section></div><p class="truth-note">'+esc(r.boundary)+'</p></section>';
    var b=document.getElementById('receiptBefore'),a=document.getElementById('receiptAfter');document.getElementById('receiptBuild').addEventListener('click',function(){body.dataset.receiptBefore=b.value.slice(0,300000);body.dataset.receiptAfter=a.value.slice(0,300000);renderReceipt();announce('Change receipt rebuilt. Canon unchanged.');});document.getElementById('receiptJson').addEventListener('click',function(){download('starsilk-canon-change-receipt.json',JSON.stringify(receipt(b.value,a.value),null,2),'application/json');});document.getElementById('receiptMd').addEventListener('click',function(){download('starsilk-canon-change-receipt.md',receiptMarkdown(receipt(b.value,a.value)),'text/markdown;charset=utf-8');});
  }
  function openLab(){reader=document.getElementById('readerWorkbench');if(reader)reader.hidden=true;panel.hidden=false;render();var first=panel.querySelector('[data-truth-tab].is-active')||panel.querySelector('button');if(first)first.focus();announce('Truth Lab opened. All analysis is local and non-canonical.');}
  function closeLab(){panel.hidden=true;if(reader){reader.hidden=false;var t=document.getElementById('readerWorkbenchToggle');if(t)t.setAttribute('aria-expanded','true');}if(launcher)launcher.focus();}
  function init(){if(!document.getElementById('canon-ledger'))return;ensureCss();panel=buildPanel();launcher=ensureLauncher();if(!launcher)return;launcher.addEventListener('click',openLab);document.getElementById('truthLabClose').addEventListener('click',closeLab);panel.querySelector('.truth-tabs').addEventListener('click',function(e){var b=e.target.closest('[data-truth-tab]');if(!b)return;activeTab=b.dataset.truthTab;render();b.focus();});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&panel&&!panel.hidden){e.preventDefault();closeLab();}});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();