import { DEFAULT_ERA_PRESETS } from "./time.ts";
import {
  DEFAULT_SETTINGS,
  SCHEMA_VERSION,
  type Entity,
  type StarMapProject,
} from "./types.ts";

const schematic = {
  canonStatus: "schematic" as const,
  positionCanon: "schematic" as const,
  sourceNote: "SCHEMATIC / NON-CANON POSITION — invented for cartographic demonstration only.",
};

function e(partial: Omit<Entity, "timeline" | "meta"> & { timeline?: Entity["timeline"]; meta?: Partial<Entity["meta"]> }): Entity {
  return {
    timeline: [],
    ...partial,
    meta: {
      ...schematic,
      ...partial.meta,
    },
  };
}

/**
 * Demonstration archive. Known names (Fallenstar Prime, Pharos Nebula,
 * Aureal Gate, Hal'Ven Cluster) may appear; every coordinate is schematic.
 * Does not invent populations, Siege Wall node counts, or unprovided dates.
 */
export function createDemoProject(): StarMapProject {
  return {
    schemaVersion: SCHEMA_VERSION,
    id: "proj-starsilk-schematic-archive",
    title: "STARSiLK Schematic Archive",
    eraPresets: DEFAULT_ERA_PRESETS,
    settings: { ...DEFAULT_SETTINGS, galaxyHistoricalTime: "main-narrative" },
    entities: [
      e({
        id: "gal-archive",
        parentId: null,
        type: "galaxy",
        name: "Schematic Archive Galaxy",
        position: { x: 0, y: 0, z: 0, unit: "schematic" },
        visual: { displayRadius: 80, color: "#55dfff" },
        meta: {
          ...schematic,
          description:
            "A forbidden Administration cartographic archive. Coordinates in this demonstration are schematic and must not be read as canon.",
          tags: ["archive", "schematic"],
          canonStatus: "schematic",
        },
      }),

      e({
        id: "sec-pharos",
        parentId: "gal-archive",
        type: "starfield",
        name: "Pharos Nebula",
        order: 0,
        position: { x: 18, y: 4, z: -6, unit: "schematic" },
        visual: { displayRadius: 8, color: "#d95d6c" },
        meta: {
          ...schematic,
          description:
            "Named nebula used schematically. Year 121: Administration attacks a Drakken forward node — Siege of the Ruby Eclipse.",
          tags: ["pharos", "blood-eclipse"],
          canonStatus: "working",
          sourceNote:
            "Name is canon-adjacent; placement is SCHEMATIC / NON-CANON POSITION.",
        },
      }),
      e({
        id: "sys-pharos-03",
        parentId: "sec-pharos",
        type: "system",
        name: "Pharos System 03",
        order: 0,
        position: { x: 2, y: 0.4, z: -1, unit: "schematic" },
        visual: { displayRadius: 1.2, color: "#e4bd46" },
        meta: {
          ...schematic,
          description: "Schematic forward-node system in the Pharos Nebula.",
          canonStatus: "schematic",
        },
      }),
      e({
        id: "star-pharos",
        parentId: "sys-pharos-03",
        type: "star",
        name: "Pharos Primary",
        visual: { displayRadius: 2.2, color: "#ffe7a8", emissive: 1.4 },
        rotationPeriod: 40,
        meta: { ...schematic, canonStatus: "schematic" },
      }),
      e({
        id: "pl-ruby",
        parentId: "sys-pharos-03",
        type: "planet",
        name: "Ruby Eclipse",
        orbit: {
          semiMajorAxis: 1.4,
          eccentricity: 0.04,
          inclination: 0.08,
          ascendingNode: 0.4,
          argumentOfPeriapsis: 0.2,
          meanAnomalyAtEpoch: 0.9,
          epoch: 0,
          period: 42,
        },
        visual: { displayRadius: 0.52, color: "#a33b48", atmosphere: true, atmosphereColor: "#d95d6c" },
        rotationPeriod: 8,
        meta: {
          ...schematic,
          description: "Schematic world associated with the Siege of the Ruby Eclipse (Year 121).",
          canonStatus: "provisional",
        },
      }),
      e({
        id: "pl-pharos-ii",
        parentId: "sys-pharos-03",
        type: "planet",
        name: "Pharos II",
        orbit: {
          semiMajorAxis: 2.6,
          eccentricity: 0.08,
          inclination: 0.12,
          ascendingNode: 1.1,
          argumentOfPeriapsis: 0.6,
          meanAnomalyAtEpoch: 2.2,
          epoch: 0,
          period: 78,
        },
        visual: { displayRadius: 0.38, color: "#4ba7db", atmosphere: true, atmosphereColor: "#7ec8e8" },
        rotationPeriod: 12,
        meta: { ...schematic, canonStatus: "schematic" },
      }),
      e({
        id: "moon-pharos-ii-a",
        parentId: "pl-pharos-ii",
        type: "moon",
        name: "Pharos II-A",
        orbit: {
          semiMajorAxis: 0.18,
          eccentricity: 0.02,
          inclination: 0.15,
          ascendingNode: 0.2,
          argumentOfPeriapsis: 0,
          meanAnomalyAtEpoch: 0.4,
          epoch: 0,
          period: 9,
        },
        visual: { displayRadius: 0.12, color: "#8fa8b8" },
        rotationPeriod: 9,
        meta: { ...schematic, canonStatus: "schematic" },
      }),

      e({
        id: "sec-fallenstar",
        parentId: "gal-archive",
        type: "starfield",
        name: "Fallenstar Region",
        order: 1,
        position: { x: -14, y: -3, z: 8, unit: "schematic" },
        visual: { displayRadius: 7, color: "#d95d6c" },
        time: { mode: "inherit" },
        meta: {
          ...schematic,
          description:
            "Named region used schematically. Year 3: first Blood Rings erected around Fallenstar Prime.",
          tags: ["fallenstar", "blood-ring"],
          canonStatus: "working",
          sourceNote: "Name is canon-adjacent; placement is SCHEMATIC / NON-CANON POSITION.",
        },
      }),
      e({
        id: "sys-fallenstar",
        parentId: "sec-fallenstar",
        type: "system",
        name: "Fallenstar System",
        order: 0,
        position: { x: -1.2, y: 0.2, z: 0.8, unit: "schematic" },
        visual: { displayRadius: 1.1, color: "#e4bd46" },
        meta: { ...schematic, canonStatus: "working" },
      }),
      e({
        id: "star-fallenstar",
        parentId: "sys-fallenstar",
        type: "star",
        name: "Fallenstar",
        visual: { displayRadius: 2.0, color: "#ffd18a", emissive: 1.1 },
        rotationPeriod: 36,
        meta: { ...schematic, canonStatus: "schematic" },
      }),
      e({
        id: "pl-fallenstar-prime",
        parentId: "sys-fallenstar",
        type: "planet",
        name: "Fallenstar Prime",
        orbit: {
          semiMajorAxis: 1.15,
          eccentricity: 0.03,
          inclination: 0.05,
          ascendingNode: 0.7,
          argumentOfPeriapsis: 0.1,
          meanAnomalyAtEpoch: 1.4,
          epoch: 0,
          period: 36,
        },
        visual: { displayRadius: 0.58, color: "#6a8b6e", atmosphere: true, atmosphereColor: "#7dbf82" },
        rotationPeriod: 10,
        meta: {
          ...schematic,
          description:
            "World around which the first Blood Rings were erected in Blood Eclipse Year 3. Coordinates schematic.",
          tags: ["fallenstar-prime", "blood-ring"],
          canonStatus: "working",
          dossierHref: "#",
        },
      }),
      e({
        id: "ring-fallenstar",
        parentId: "pl-fallenstar-prime",
        type: "bloodRing",
        name: "First Blood Ring",
        orbit: {
          semiMajorAxis: 0.22,
          eccentricity: 0,
          inclination: 0.18,
          ascendingNode: 0.3,
          argumentOfPeriapsis: 0,
          meanAnomalyAtEpoch: 0,
          epoch: 0,
          period: 14,
        },
        visual: {
          displayRadius: 1.35,
          color: "#6a1018",
          ringThickness: 0.09,
          ringInner: 1.05,
          ringOuter: 1.55,
        },
        timeline: [
          {
            id: "evt-blood-ring-formed",
            time: 3,
            label: "Blood Ring formed",
            eventType: "bloodRingCreated",
            canonStatus: "locked",
            sourceNote:
              "Year 3: First Blood Rings erected around Fallenstar Prime. A Blood Ring is a huge solid orbital band created from the processed remains and biospheric material of a murdered world. “Your sky is built from your dead.”",
          },
        ],
        meta: {
          canonStatus: "locked",
          positionCanon: "schematic",
          description:
            "Solid orbital band of vitrified black-red composite: biological residue, ash, fats, minerals, Drakken processing material. Not an asteroid belt, not Saturn-like dust, not jewelry.",
          tags: ["blood-ring"],
          sourceNote: "Creation era Year 3 is a locked chronology anchor. Placement remains schematic.",
        },
      }),
      e({
        id: "pl-fallenstar-minor",
        parentId: "sys-fallenstar",
        type: "planet",
        name: "Fallenstar Minor",
        orbit: {
          semiMajorAxis: 2.1,
          eccentricity: 0.11,
          inclination: 0.2,
          ascendingNode: 2.1,
          argumentOfPeriapsis: 0.8,
          meanAnomalyAtEpoch: 4.0,
          epoch: 0,
          period: 64,
        },
        visual: { displayRadius: 0.3, color: "#8a6a4a" },
        rotationPeriod: 16,
        meta: { ...schematic, canonStatus: "schematic" },
      }),

      e({
        id: "sec-aureal",
        parentId: "gal-archive",
        type: "starfield",
        name: "Aureal Gate",
        order: 2,
        position: { x: 6, y: -10, z: 16, unit: "schematic" },
        visual: { displayRadius: 6.5, color: "#55dfff" },
        meta: {
          ...schematic,
          description:
            "Named region used schematically. Year 170: final collapse at the Aureal Gate. Drakken use Starsilk against gods for the first time.",
          tags: ["aureal", "heliocide"],
          canonStatus: "working",
          sourceNote: "Name is canon-adjacent; placement is SCHEMATIC / NON-CANON POSITION.",
        },
      }),
      e({
        id: "sys-aureal",
        parentId: "sec-aureal",
        type: "system",
        name: "Aureal System",
        order: 0,
        position: { x: 0.6, y: -0.8, z: 1.4, unit: "schematic" },
        visual: { displayRadius: 1.1, color: "#a6efff" },
        meta: {
          ...schematic,
          description:
            "Schematic system at the Aureal Gate. Pulling Starsilk from the center of a star collapses it immediately into a black hole and destroys its star system.",
          canonStatus: "working",
        },
      }),
      e({
        id: "star-aureal",
        parentId: "sys-aureal",
        type: "star",
        name: "Aureal",
        visual: { displayRadius: 2.4, color: "#fff4d2", emissive: 1.6 },
        rotationPeriod: 28,
        timeline: [
          {
            id: "evt-aureal-collapse",
            time: 170,
            label: "Starsilk extraction collapse",
            eventType: "starsilkExtractionCollapse",
            canonStatus: "locked",
            sourceNote:
              "Year 170: final collapse at the Aureal Gate. Starsilk is a literal programmable cosmological substance — not sentient. Extraction from a stellar core collapses the star into a black hole and historically destroys the system. Afterward Shard-God Tiger collapses huge numbers of stars, establishing the Siege Wall.",
          },
        ],
        meta: {
          ...schematic,
          description:
            "Schematic primary. After Year 170 this body is a black hole and the system is historically destroyed. Backward scrubbing restores visualization of the earlier state; it does not imply resurrection.",
          canonStatus: "working",
          tags: ["heliocide", "starsilk"],
        },
      }),
      e({
        id: "pl-aureal-i",
        parentId: "sys-aureal",
        type: "planet",
        name: "Aureal I",
        orbit: {
          semiMajorAxis: 1.05,
          eccentricity: 0.05,
          inclination: 0.04,
          ascendingNode: 0.2,
          argumentOfPeriapsis: 0.3,
          meanAnomalyAtEpoch: 0.1,
          epoch: 0,
          period: 30,
        },
        visual: { displayRadius: 0.42, color: "#c9d5df", atmosphere: true },
        rotationPeriod: 11,
        timeline: [
          {
            id: "evt-aureal-i-lost",
            time: 170,
            label: "System historically destroyed",
            eventType: "destroyed",
            canonStatus: "locked",
            sourceNote: "Destroyed with the Aureal collapse. No survivors, debris belts, or recovery are authored.",
          },
        ],
        meta: { ...schematic, canonStatus: "schematic" },
      }),

      e({
        id: "sec-halven",
        parentId: "gal-archive",
        type: "starfield",
        name: "Hal'Ven Cluster",
        order: 3,
        position: { x: -20, y: 12, z: -10, unit: "schematic" },
        visual: { displayRadius: 7.5, color: "#4ba7db" },
        meta: {
          ...schematic,
          description: "Named cluster used schematically.",
          canonStatus: "working",
          sourceNote: "Name is canon-adjacent; placement is SCHEMATIC / NON-CANON POSITION.",
        },
      }),
      e({
        id: "sys-halven-watch",
        parentId: "sec-halven",
        type: "system",
        name: "Hal'Ven Watch",
        order: 0,
        position: { x: -1.6, y: 1.1, z: -0.7, unit: "schematic" },
        visual: { displayRadius: 1.0, color: "#7dbf82" },
        meta: { ...schematic, canonStatus: "schematic" },
      }),
      e({
        id: "star-halven",
        parentId: "sys-halven-watch",
        type: "star",
        name: "Watchfire",
        visual: { displayRadius: 1.7, color: "#ffc978", emissive: 0.9 },
        rotationPeriod: 44,
        meta: { ...schematic, canonStatus: "schematic" },
      }),
      e({
        id: "pl-halven",
        parentId: "sys-halven-watch",
        type: "planet",
        name: "Watchfall",
        orbit: {
          semiMajorAxis: 1.7,
          eccentricity: 0.06,
          inclination: 0.09,
          ascendingNode: 1.6,
          argumentOfPeriapsis: 0.5,
          meanAnomalyAtEpoch: 3.1,
          epoch: 0,
          period: 52,
        },
        visual: { displayRadius: 0.44, color: "#4b7a6a", atmosphere: true, atmosphereColor: "#7dbf82" },
        rotationPeriod: 13,
        meta: { ...schematic, canonStatus: "schematic" },
      }),

      e({
        id: "sec-drakken",
        parentId: "gal-archive",
        type: "starfield",
        name: "Drakken Domain",
        order: 4,
        position: { x: 4, y: 16, z: 4, unit: "schematic" },
        visual: { displayRadius: 11, color: "#5a3038" },
        meta: {
          ...schematic,
          description:
            "Schematic region of Drakken activity. Drakken are elemental terraforming entities produced by the Notebook Program — not ordinary dragons, monsters, kaiju, or aliens. The Siege Wall contained them; it did not annihilate them.",
          tags: ["drakken"],
          canonStatus: "working",
          sourceNote: "Domain extent is SCHEMATIC / NON-CANON POSITION.",
        },
      }),
      e({
        id: "sys-drakken-node",
        parentId: "sec-drakken",
        type: "system",
        name: "Forward Node (schematic)",
        order: 0,
        position: { x: 0.8, y: 1.4, z: 0.3, unit: "schematic" },
        visual: { displayRadius: 1.0, color: "#d95d6c" },
        meta: { ...schematic, canonStatus: "schematic" },
      }),
      e({
        id: "star-drakken",
        parentId: "sys-drakken-node",
        type: "star",
        name: "Node Primary",
        visual: { displayRadius: 1.8, color: "#ffb48a", emissive: 0.8 },
        rotationPeriod: 50,
        meta: { ...schematic, canonStatus: "schematic" },
      }),
      e({
        id: "pl-replaced",
        parentId: "sys-drakken-node",
        type: "planet",
        name: "Replaced World",
        orbit: {
          semiMajorAxis: 1.3,
          eccentricity: 0.02,
          inclination: 0.03,
          ascendingNode: 0.5,
          argumentOfPeriapsis: 0.2,
          meanAnomalyAtEpoch: 5.2,
          epoch: 0,
          period: 40,
        },
        visual: { displayRadius: 0.48, color: "#3a2a22", atmosphere: true, atmosphereColor: "#6a3030" },
        rotationPeriod: 14,
        meta: {
          ...schematic,
          description:
            "Schematic world illustrating Drakken replacement of ecosystems, geology, atmospheres, settlements, cultures, populations, and stellar infrastructure.",
          canonStatus: "schematic",
        },
      }),

      e({
        id: "lss-siege-wall",
        parentId: "gal-archive",
        type: "largeScaleStructure",
        name: "Siege Wall",
        order: 90,
        position: { x: 2, y: 8, z: 2, unit: "schematic" },
        visual: { displayRadius: 22, color: "#05070d" },
        timeline: [
          {
            id: "evt-siege-wall",
            time: "post-siege-wall",
            label: "Siege Wall established",
            eventType: "siegeWallFormed",
            canonStatus: "locked",
            sourceNote:
              "After the Aureal Gate, Shard-God Tiger collapses huge numbers of stars. Those stellar deaths establish the Siege Wall. It is not a literal wall, fence, lattice, or force field. From inhabited worlds it manifests as an enormous swath of black absence across the night sky. Node count is not authored here.",
          },
        ],
        meta: {
          canonStatus: "locked",
          positionCanon: "schematic",
          description:
            "Large-scale containment architecture formed from stars collapsed into black holes around Drakken territory. Primary representation: lost stars, missing light, void. Analyst overlay is non-diegetic and off by default.",
          tags: ["siege-wall"],
          sourceNote:
            "Geometry in this archive is schematic. No exact node count is claimed.",
        },
      }),
      e({
        id: "bh-wall-a",
        parentId: "lss-siege-wall",
        type: "blackHole",
        name: "Lock (schematic)",
        position: { x: 10, y: 9, z: 3, unit: "schematic" },
        visual: { displayRadius: 0.55, color: "#000000" },
        timeline: [
          {
            id: "evt-lock-a",
            time: "post-siege-wall",
            label: "Collapsed lock",
            eventType: "created",
            canonStatus: "schematic",
            sourceNote: "Schematic lock node — not a claimed canon count.",
          },
        ],
        meta: {
          ...schematic,
          description: "Schematic collapsed-star lock. Not a census of the Wall.",
        },
      }),
      e({
        id: "bh-wall-b",
        parentId: "lss-siege-wall",
        type: "blackHole",
        name: "Lock (schematic)",
        position: { x: -2, y: 14, z: 6, unit: "schematic" },
        visual: { displayRadius: 0.5, color: "#000000" },
        timeline: [
          {
            id: "evt-lock-b",
            time: "post-siege-wall",
            label: "Collapsed lock",
            eventType: "created",
            canonStatus: "schematic",
            sourceNote: "Schematic lock node — not a claimed canon count.",
          },
        ],
        meta: { ...schematic, description: "Schematic collapsed-star lock." },
      }),
      e({
        id: "bh-wall-c",
        parentId: "lss-siege-wall",
        type: "blackHole",
        name: "Lock (schematic)",
        position: { x: 8, y: 18, z: -2, unit: "schematic" },
        visual: { displayRadius: 0.48, color: "#000000" },
        timeline: [
          {
            id: "evt-lock-c",
            time: "post-siege-wall",
            label: "Collapsed lock",
            eventType: "created",
            canonStatus: "schematic",
            sourceNote: "Schematic lock node — not a claimed canon count.",
          },
        ],
        meta: { ...schematic, description: "Schematic collapsed-star lock." },
      }),
    ],
  };
}
